// Source: https://gist.github.com/ssskip/5a94bfcd2835bf1dea52
// https://github.com/stefangabos/world_countries/tree/master
// https://www.worldcountryguide.com/
// Some information has been edited.

const Map<String, Map<String, dynamic>> countryInfo = {
  "AD": {
    "name": "Andorra",
    "shortName": "Andorra",
    "nativeName": "Andorra",
    "capital": "Andorra la Vella",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "376",
    "timeZoneInCapital": "Europe/Andorra",
    "alpha2": "AD",
    "alpha3": "AND",
    "numeric": "20",
    "tld": "ad",
    "fips": "AN"
  },
  "AE": {
    "name": "United Arab Emirates (the)",
    "shortName": "UAE",
    "nativeName": "دولة الإمارات العربية المتحدة",
    "capital": "Abu Dhabi",
    "continent": "Asia",
    "currency": "Dirham",
    "callingCode": "971",
    "timeZoneInCapital": "Asia/Dubai",
    "alpha2": "AE",
    "alpha3": "ARE",
    "numeric": "784",
    "tld": "ae",
    "fips": "AE"
  },
  "AF": {
    "name": "Afghanistan",
    "shortName": "Afghanistan",
    "nativeName": "افغانستان",
    "capital": "Kabul",
    "continent": "Asia",
    "currency": "Afghani",
    "callingCode": "93",
    "timeZoneInCapital": "Asia/Kabul",
    "alpha2": "AF",
    "alpha3": "AFG",
    "numeric": "4",
    "tld": "af",
    "fips": "AF"
  },
  "AG": {
    "name": "Antigua and Barbuda",
    "shortName": "Antigua and Barbuda",
    "nativeName": "Antigua and Barbuda",
    "capital": "St. John's",
    "continent": "North America",
    "currency": "Dollar",
    "callingCode": "1-268",
    "timeZoneInCapital": "America/Antigua",
    "alpha2": "AG",
    "alpha3": "ATG",
    "numeric": "28",
    "tld": "ag",
    "fips": "AC"
  },
  "AI": {
    "name": "Anguilla",
    "shortName": "Anguilla",
    "nativeName": "Anguilla",
    "capital": "The Valley",
    "continent": "North America",
    "currency": "Dollar",
    "callingCode": "1-264",
    "timeZoneInCapital": "America/Port_of_Spain",
    "alpha2": "AI",
    "alpha3": "AIA",
    "numeric": "660",
    "tld": "ai",
    "fips": "AV"
  },
  "AL": {
    "name": "Albania",
    "shortName": "Albania",
    "nativeName": "Shqipëria",
    "capital": "Tirana",
    "continent": "Europe",
    "currency": "Lek",
    "callingCode": "355",
    "timeZoneInCapital": "Europe/Tirane",
    "alpha2": "AL",
    "alpha3": "ALB",
    "numeric": "8",
    "tld": "al",
    "fips": "AL"
  },
  "AM": {
    "name": "Armenia",
    "shortName": "Armenia",
    "nativeName": "Հայաստան",
    "capital": "Yerevan",
    "continent": "Asia",
    "currency": "Dram",
    "callingCode": "374",
    "timeZoneInCapital": "Asia/Yerevan",
    "alpha2": "AM",
    "alpha3": "ARM",
    "numeric": "51",
    "tld": "am",
    "fips": "AM"
  },
  "AN": {
    "name": "Netherlands Antilles",
    "shortName": "Netherlands Antilles",
    "nativeName": "Netherlands Antilles",
    "capital": "Willemstad",
    "continent": "North America",
    "currency": "Guilder",
    "callingCode": "599",
    "timeZoneInCapital": "America/Curacao",
    "alpha2": "AN",
    "alpha3": "ANT",
    "numeric": "530",
    "tld": "an",
    "fips": "NT"
  },
  "AO": {
    "name": "Angola",
    "shortName": "Angola",
    "nativeName": "Angola",
    "capital": "Luanda",
    "continent": "Africa",
    "currency": "Kwanza",
    "callingCode": "244",
    "timeZoneInCapital": "Africa/Lagos",
    "alpha2": "AO",
    "alpha3": "AGO",
    "numeric": "24",
    "tld": "ao",
    "fips": "AO"
  },
  "AQ": {
    "name": "Antarctica",
    "shortName": "Antarctica",
    "nativeName": "Antarctica",
    "capital": "",
    "continent": "Antarctica",
    "currency": "",
    "callingCode": "672",
    "timeZoneInCapital": "Antarctica/Troll",
    "alpha2": "AQ",
    "alpha3": "ATA",
    "numeric": "10",
    "tld": "aq",
    "fips": "AY"
  },
  "AR": {
    "name": "Argentina",
    "shortName": "Argentina",
    "nativeName": "Argentina",
    "capital": "Buenos Aires",
    "continent": "South America",
    "currency": "Peso",
    "callingCode": "54",
    "timeZoneInCapital": "America/Argentina/Buenos_Aires",
    "alpha2": "AR",
    "alpha3": "ARG",
    "numeric": "32",
    "tld": "ar",
    "fips": "AR"
  },
  "AS": {
    "name": "American Samoa",
    "shortName": "American Samoa",
    "nativeName": "American Samoa",
    "capital": "Pago Pago",
    "continent": "Oceania",
    "currency": "Dollar",
    "callingCode": "1-684",
    "timeZoneInCapital": "Pacific/Pago_Pago",
    "alpha2": "AS",
    "alpha3": "ASM",
    "numeric": "16",
    "tld": "as",
    "fips": "AQ"
  },
  "AT": {
    "name": "Austria",
    "shortName": "Austria",
    "nativeName": "Österreich",
    "capital": "Vienna",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "43",
    "timeZoneInCapital": "Europe/Vienna",
    "alpha2": "AT",
    "alpha3": "AUT",
    "numeric": "40",
    "tld": "at",
    "fips": "AU"
  },
  "AU": {
    "name": "Australia",
    "shortName": "Australia",
    "nativeName": "Australia",
    "capital": "Canberra",
    "continent": "Oceania",
    "currency": "Dollar",
    "callingCode": "61",
    "timeZoneInCapital": "Australia/Sydney",
    "alpha2": "AU",
    "alpha3": "AUS",
    "numeric": "36",
    "tld": "au",
    "fips": "AS"
  },
  "AW": {
    "name": "Aruba",
    "shortName": "Aruba",
    "nativeName": "Aruba",
    "capital": "Oranjestad",
    "continent": "North America",
    "currency": "Guilder",
    "callingCode": "297",
    "timeZoneInCapital": "America/Curacao",
    "alpha2": "AW",
    "alpha3": "ABW",
    "numeric": "533",
    "tld": "aw",
    "fips": "AA"
  },
  "AX": {
    "name": "Åland Islands",
    "shortName": "Aland Islands",
    "nativeName": "Åland",
    "capital": "Mariehamn",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "358",
    "timeZoneInCapital": "Europe/Mariehamn",
    "alpha2": "AX",
    "alpha3": "ALA",
    "numeric": "248",
    "tld": "ax",
    "fips": "FI"
  },
  "AZ": {
    "name": "Azerbaijan",
    "shortName": "Azerbaijan",
    "nativeName": "Azərbaycan",
    "capital": "Baku",
    "continent": "Asia",
    "currency": "Manat",
    "callingCode": "994",
    "timeZoneInCapital": "Asia/Baku",
    "alpha2": "AZ",
    "alpha3": "AZE",
    "numeric": "31",
    "tld": "az",
    "fips": "AJ"
  },
  "BA": {
    "name": "Bosnia and Herzegovina",
    "shortName": "Bosnia and Herzegovina",
    "nativeName": "Bosna i Hercegovina",
    "capital": "Sarajevo",
    "continent": "Europe",
    "currency": "Marka",
    "callingCode": "387",
    "timeZoneInCapital": "Europe/Belgrade",
    "alpha2": "BA",
    "alpha3": "BIH",
    "numeric": "70",
    "tld": "ba",
    "fips": "BK"
  },
  "BB": {
    "name": "Barbados",
    "shortName": "Barbados",
    "nativeName": "Barbados",
    "capital": "Bridgetown",
    "continent": "North America",
    "currency": "Dollar",
    "callingCode": "1-246",
    "timeZoneInCapital": "America/Barbados",
    "alpha2": "BB",
    "alpha3": "BRB",
    "numeric": "52",
    "tld": "bb",
    "fips": "BB"
  },
  "BD": {
    "name": "Bangladesh",
    "shortName": "Bangladesh",
    "nativeName": "Bangladesh",
    "capital": "Dhaka",
    "continent": "Asia",
    "currency": "Taka",
    "callingCode": "880",
    "timeZoneInCapital": "Asia/Dhaka",
    "alpha2": "BD",
    "alpha3": "BGD",
    "numeric": "50",
    "tld": "bd",
    "fips": "BG"
  },
  "BE": {
    "name": "Belgium",
    "shortName": "Belgium",
    "nativeName": "België",
    "capital": "Brussels",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "32",
    "timeZoneInCapital": "Europe/Brussels",
    "alpha2": "BE",
    "alpha3": "BEL",
    "numeric": "56",
    "tld": "be",
    "fips": "BE"
  },
  "BF": {
    "name": "Burkina Faso",
    "shortName": "Burkina Faso",
    "nativeName": "Burkina Faso",
    "capital": "Ouagadougou",
    "continent": "Africa",
    "currency": "Franc",
    "callingCode": "226",
    "timeZoneInCapital": "Africa/Abidjan",
    "alpha2": "BF",
    "alpha3": "BFA",
    "numeric": "854",
    "tld": "bf",
    "fips": "UV"
  },
  "BG": {
    "name": "Bulgaria",
    "shortName": "Bulgaria",
    "nativeName": "България",
    "capital": "Sofia",
    "continent": "Europe",
    "currency": "Lev",
    "callingCode": "359",
    "timeZoneInCapital": "Europe/Sofia",
    "alpha2": "BG",
    "alpha3": "BGR",
    "numeric": "100",
    "tld": "bg",
    "fips": "BU"
  },
  "BH": {
    "name": "Bahrain",
    "shortName": "Bahrain",
    "nativeName": "‏البحرين",
    "capital": "Manama",
    "continent": "Asia",
    "currency": "Dinar",
    "callingCode": "973",
    "timeZoneInCapital": "Asia/Bahrain",
    "alpha2": "BH",
    "alpha3": "BHR",
    "numeric": "48",
    "tld": "bh",
    "fips": "BA"
  },
  "BI": {
    "name": "Burundi",
    "shortName": "Burundi",
    "nativeName": "Burundi",
    "capital": "Bujumbura",
    "continent": "Africa",
    "currency": "Franc",
    "callingCode": "257",
    "timeZoneInCapital": "Africa/Maputo",
    "alpha2": "BI",
    "alpha3": "BDI",
    "numeric": "108",
    "tld": "bi",
    "fips": "BY"
  },
  "BJ": {
    "name": "Benin",
    "shortName": "Benin",
    "nativeName": "Bénin",
    "capital": "Porto-Novo",
    "continent": "Africa",
    "currency": "Franc",
    "callingCode": "229",
    "timeZoneInCapital": "Africa/Lagos",
    "alpha2": "BJ",
    "alpha3": "BEN",
    "numeric": "204",
    "tld": "bj",
    "fips": "BN"
  },
  "BL": {
    "name": "Saint Barthélemy",
    "shortName": "Saint Barthelemy",
    "nativeName": "Saint-Barthélemy",
    "capital": "Gustavia",
    "continent": "North America",
    "currency": "Euro",
    "callingCode": "590",
    "timeZoneInCapital": "America/Port_of_Spain",
    "alpha2": "BL",
    "alpha3": "BLM",
    "numeric": "652",
    "tld": "gp",
    "fips": "TB"
  },
  "BM": {
    "name": "Bermuda",
    "shortName": "Bermuda",
    "nativeName": "Bermuda",
    "capital": "Hamilton",
    "continent": "North America",
    "currency": "Dollar",
    "callingCode": "1-441",
    "timeZoneInCapital": "Atlantic/Bermuda",
    "alpha2": "BM",
    "alpha3": "BMU",
    "numeric": "60",
    "tld": "bm",
    "fips": "BD"
  },
  "BN": {
    "name": "Brunei Darussalam",
    "shortName": "Brunei",
    "nativeName": "Negara Brunei Darussalam",
    "capital": "Bandar Seri Begawan",
    "continent": "Asia",
    "currency": "Dollar",
    "callingCode": "673",
    "timeZoneInCapital": "Asia/Brunei",
    "alpha2": "BN",
    "alpha3": "BRN",
    "numeric": "96",
    "tld": "bn",
    "fips": "BX"
  },
  "BO": {
    "name": "Bolivia (Plurinational State of)",
    "shortName": "Bolivia",
    "nativeName": "Bolivia",
    "capital": "Sucre",
    "continent": "South America",
    "currency": "Boliviano",
    "callingCode": "591",
    "timeZoneInCapital": "America/La_Paz",
    "alpha2": "BO",
    "alpha3": "BOL",
    "numeric": "68",
    "tld": "bo",
    "fips": "BL"
  },
  "BR": {
    "name": "Brazil",
    "shortName": "Brazil",
    "nativeName": "Brasil",
    "capital": "Brasilia",
    "continent": "South America",
    "currency": "Real",
    "callingCode": "55",
    "timeZoneInCapital": "America/Sao_Paulo",
    "alpha2": "BR",
    "alpha3": "BRA",
    "numeric": "76",
    "tld": "br",
    "fips": "BR"
  },
  "BS": {
    "name": "Bahamas (the)",
    "shortName": "Bahamas",
    "nativeName": "Bahamas",
    "capital": "Nassau",
    "continent": "North America",
    "currency": "Dollar",
    "callingCode": "1-242",
    "timeZoneInCapital": "America/Nassau",
    "alpha2": "BS",
    "alpha3": "BHS",
    "numeric": "44",
    "tld": "bs",
    "fips": "BF"
  },
  "BT": {
    "name": "Bhutan",
    "shortName": "Bhutan",
    "nativeName": "ʼbrug-yul",
    "capital": "Thimphu",
    "continent": "Asia",
    "currency": "Ngultrum",
    "callingCode": "975",
    "timeZoneInCapital": "Asia/Thimphu",
    "alpha2": "BT",
    "alpha3": "BTN",
    "numeric": "64",
    "tld": "bt",
    "fips": "BT"
  },
  "BV": {
    "name": "Bouvet Island",
    "shortName": "Bouvet Island",
    "nativeName": "Bouvetøya",
    "capital": "",
    "continent": "Antarctica",
    "currency": "Krone",
    "callingCode": "47",
    "timeZoneInCapital": "",
    "alpha2": "BV",
    "alpha3": "BVT",
    "numeric": "74",
    "tld": "bv",
    "fips": "BV"
  },
  "BW": {
    "name": "Botswana",
    "shortName": "Botswana",
    "nativeName": "Botswana",
    "capital": "Gaborone",
    "continent": "Africa",
    "currency": "Pula",
    "callingCode": "267",
    "timeZoneInCapital": "Africa/Maputo",
    "alpha2": "BW",
    "alpha3": "BWA",
    "numeric": "72",
    "tld": "bw",
    "fips": "BC"
  },
  "BY": {
    "name": "Belarus",
    "shortName": "Belarus",
    "nativeName": "Белару́сь",
    "capital": "Minsk",
    "continent": "Europe",
    "currency": "Ruble",
    "callingCode": "375",
    "timeZoneInCapital": "Europe/Minsk",
    "alpha2": "BY",
    "alpha3": "BLR",
    "numeric": "112",
    "tld": "by",
    "fips": "BO"
  },
  "BZ": {
    "name": "Belize",
    "shortName": "Belize",
    "nativeName": "Belize",
    "capital": "Belmopan",
    "continent": "North America",
    "currency": "Dollar",
    "callingCode": "501",
    "timeZoneInCapital": "America/Belize",
    "alpha2": "BZ",
    "alpha3": "BLZ",
    "numeric": "84",
    "tld": "bz",
    "fips": "BH"
  },
  "CA": {
    "name": "Canada",
    "shortName": "Canada",
    "nativeName": "Canada",
    "capital": "Ottawa",
    "continent": "North America",
    "currency": "Dollar",
    "callingCode": "1",
    "timeZoneInCapital": "America/Toronto",
    "alpha2": "CA",
    "alpha3": "CAN",
    "numeric": "124",
    "tld": "ca",
    "fips": "CA"
  },
  "CC": {
    "name": "Cocos (Keeling) Islands (the)",
    "shortName": "Cocos Islands",
    "nativeName": "Cocos (Keeling) Islands",
    "capital": "West Island",
    "continent": "Asia",
    "currency": "Dollar",
    "callingCode": "61",
    "timeZoneInCapital": "Indian/Cocos",
    "alpha2": "CC",
    "alpha3": "CCK",
    "numeric": "166",
    "tld": "cc",
    "fips": "CK"
  },
  "CD": {
    "name": "Congo (the Democratic Republic of the)",
    "shortName": "Democratic Republic of the Congo",
    "nativeName": "République démocratique du Congo",
    "capital": "Kinshasa",
    "continent": "Africa",
    "currency": "Franc",
    "callingCode": "243",
    "timeZoneInCapital": "Africa/Lagos",
    "alpha2": "CD",
    "alpha3": "COD",
    "numeric": "180",
    "tld": "cd",
    "fips": "CG"
  },
  "CF": {
    "name": "Central African Republic (the)",
    "shortName": "Central African Republic",
    "nativeName": "Ködörösêse tî Bêafrîka",
    "capital": "Bangui",
    "continent": "Africa",
    "currency": "Franc",
    "callingCode": "236",
    "timeZoneInCapital": "Africa/Lagos",
    "alpha2": "CF",
    "alpha3": "CAF",
    "numeric": "140",
    "tld": "cf",
    "fips": "CT"
  },
  "CG": {
    "name": "Congo (the)",
    "shortName": "Republic of the Congo",
    "nativeName": "République du Congo",
    "capital": "Brazzaville",
    "continent": "Africa",
    "currency": "Franc",
    "callingCode": "242",
    "timeZoneInCapital": "Africa/Lagos",
    "alpha2": "CG",
    "alpha3": "COG",
    "numeric": "178",
    "tld": "cg",
    "fips": "CF"
  },
  "CH": {
    "name": "Switzerland",
    "shortName": "Switzerland",
    "nativeName": "Schweiz",
    "capital": "Berne",
    "continent": "Europe",
    "currency": "Franc",
    "callingCode": "41",
    "timeZoneInCapital": "Europe/Zurich",
    "alpha2": "CH",
    "alpha3": "CHE",
    "numeric": "756",
    "tld": "ch",
    "fips": "SZ"
  },
  "CI": {
    "name": "Côte d'Ivoire",
    "shortName": "Ivory Coast",
    "nativeName": "Côte d'Ivoire",
    "capital": "Yamoussoukro",
    "continent": "Africa",
    "currency": "Franc",
    "callingCode": "225",
    "timeZoneInCapital": "Africa/Abidjan",
    "alpha2": "CI",
    "alpha3": "CIV",
    "numeric": "384",
    "tld": "ci",
    "fips": "IV"
  },
  "CK": {
    "name": "Cook Islands (the)",
    "shortName": "Cook Islands",
    "nativeName": "Cook Islands",
    "capital": "Avarua",
    "continent": "Oceania",
    "currency": "Dollar",
    "callingCode": "682",
    "timeZoneInCapital": "Pacific/Rarotonga",
    "alpha2": "CK",
    "alpha3": "COK",
    "numeric": "184",
    "tld": "ck",
    "fips": "CW"
  },
  "CL": {
    "name": "Chile",
    "shortName": "Chile",
    "nativeName": "Chile",
    "capital": "Santiago",
    "continent": "South America",
    "currency": "Peso",
    "callingCode": "56",
    "timeZoneInCapital": "America/Santiago",
    "alpha2": "CL",
    "alpha3": "CHL",
    "numeric": "152",
    "tld": "cl",
    "fips": "CI"
  },
  "CM": {
    "name": "Cameroon",
    "shortName": "Cameroon",
    "nativeName": "Cameroon",
    "capital": "Yaounde",
    "continent": "Africa",
    "currency": "Franc",
    "callingCode": "237",
    "timeZoneInCapital": "Africa/Lagos",
    "alpha2": "CM",
    "alpha3": "CMR",
    "numeric": "120",
    "tld": "cm",
    "fips": "CM"
  },
  "CN": {
    "name": "China",
    "shortName": "China",
    "nativeName": "中国",
    "capital": "Beijing",
    "continent": "Asia",
    "currency": "Yuan Renminbi",
    "callingCode": "86",
    "timeZoneInCapital": "Asia/Shanghai",
    "alpha2": "CN",
    "alpha3": "CHN",
    "numeric": "156",
    "tld": "cn",
    "fips": "CH"
  },
  "CO": {
    "name": "Colombia",
    "shortName": "Colombia",
    "nativeName": "Colombia",
    "capital": "Bogota",
    "continent": "South America",
    "currency": "Peso",
    "callingCode": "57",
    "timeZoneInCapital": "America/Bogota",
    "alpha2": "CO",
    "alpha3": "COL",
    "numeric": "170",
    "tld": "co",
    "fips": "CO"
  },
  "CR": {
    "name": "Costa Rica",
    "shortName": "Costa Rica",
    "nativeName": "Costa Rica",
    "capital": "San Jose",
    "continent": "North America",
    "currency": "Colon",
    "callingCode": "506",
    "timeZoneInCapital": "America/Costa_Rica",
    "alpha2": "CR",
    "alpha3": "CRI",
    "numeric": "188",
    "tld": "cr",
    "fips": "CS"
  },
  "CU": {
    "name": "Cuba",
    "shortName": "Cuba",
    "nativeName": "Cuba",
    "capital": "Havana",
    "continent": "North America",
    "currency": "Peso",
    "callingCode": "53",
    "timeZoneInCapital": "America/Havana",
    "alpha2": "CU",
    "alpha3": "CUB",
    "numeric": "192",
    "tld": "cu",
    "fips": "CU"
  },
  "CV": {
    "name": "Cabo Verde",
    "shortName": "Cape Verde",
    "nativeName": "Cabo Verde",
    "capital": "Praia",
    "continent": "Africa",
    "currency": "Escudo",
    "callingCode": "238",
    "timeZoneInCapital": "Atlantic/Cape_Verde",
    "alpha2": "CV",
    "alpha3": "CPV",
    "numeric": "132",
    "tld": "cv",
    "fips": "CV"
  },
  "CW": {
    "name": "Curaçao",
    "shortName": "Curacao",
    "nativeName": "Curaçao",
    "capital": "Willemstad",
    "continent": "North America",
    "currency": "Guilder",
    "callingCode": "599",
    "timeZoneInCapital": "America/Curacao",
    "alpha2": "CW",
    "alpha3": "CUW",
    "numeric": "531",
    "tld": "cw",
    "fips": "UC"
  },
  "CX": {
    "name": "Christmas Island",
    "shortName": "Christmas Island",
    "nativeName": "Christmas Island",
    "capital": "Flying Fish Cove",
    "continent": "Asia",
    "currency": "Dollar",
    "callingCode": "61",
    "timeZoneInCapital": "Indian/Christmas",
    "alpha2": "CX",
    "alpha3": "CXR",
    "numeric": "162",
    "tld": "cx",
    "fips": "KT"
  },
  "CY": {
    "name": "Cyprus",
    "shortName": "Cyprus",
    "nativeName": "Κύπρος",
    "capital": "Nicosia",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "357",
    "timeZoneInCapital": "Asia/Nicosia",
    "alpha2": "CY",
    "alpha3": "CYP",
    "numeric": "196",
    "tld": "cy",
    "fips": "CY"
  },
  "CZ": {
    "name": "Czechia",
    "shortName": "Czech Republic",
    "nativeName": "Česká republika",
    "capital": "Prague",
    "continent": "Europe",
    "currency": "Koruna",
    "callingCode": "420",
    "timeZoneInCapital": "Europe/Prague",
    "alpha2": "CZ",
    "alpha3": "CZE",
    "numeric": "203",
    "tld": "cz",
    "fips": "EZ"
  },
  "DE": {
    "name": "Germany",
    "shortName": "Germany",
    "nativeName": "Deutschland",
    "capital": "Berlin",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "49",
    "timeZoneInCapital": "Europe/Berlin",
    "alpha2": "DE",
    "alpha3": "DEU",
    "numeric": "276",
    "tld": "de",
    "fips": "GM"
  },
  "DJ": {
    "name": "Djibouti",
    "shortName": "Djibouti",
    "nativeName": "Djibouti",
    "capital": "Djibouti",
    "continent": "Africa",
    "currency": "Franc",
    "callingCode": "253",
    "timeZoneInCapital": "Africa/Djibouti",
    "alpha2": "DJ",
    "alpha3": "DJI",
    "numeric": "262",
    "tld": "dj",
    "fips": "DJ"
  },
  "DK": {
    "name": "Denmark",
    "shortName": "Denmark",
    "nativeName": "Danmark",
    "capital": "Copenhagen",
    "continent": "Europe",
    "currency": "Krone",
    "callingCode": "45",
    "timeZoneInCapital": "Europe/Copenhagen",
    "alpha2": "DK",
    "alpha3": "DNK",
    "numeric": "208",
    "tld": "dk",
    "fips": "DA"
  },
  "DM": {
    "name": "Dominica",
    "shortName": "Dominica",
    "nativeName": "Dominica",
    "capital": "Roseau",
    "continent": "North America",
    "currency": "Dollar",
    "callingCode": "1-767",
    "timeZoneInCapital": "America/Port_of_Spain",
    "alpha2": "DM",
    "alpha3": "DMA",
    "numeric": "212",
    "tld": "dm",
    "fips": "DO"
  },
  "DO": {
    "name": "Dominican Republic (the)",
    "shortName": "Dominican Republic",
    "nativeName": "República Dominicana",
    "capital": "Santo Domingo",
    "continent": "North America",
    "currency": "Peso",
    "callingCode": "1-809, 1-829, 1-849",
    "timeZoneInCapital": "America/Santo_Domingo",
    "alpha2": "DO",
    "alpha3": "DOM",
    "numeric": "214",
    "tld": "do",
    "fips": "DR"
  },
  "DZ": {
    "name": "Algeria",
    "shortName": "Algeria",
    "nativeName": "الجزائر",
    "capital": "Algiers",
    "continent": "Africa",
    "currency": "Dinar",
    "callingCode": "213",
    "timeZoneInCapital": "Africa/Algiers",
    "alpha2": "DZ",
    "alpha3": "DZA",
    "numeric": "12",
    "tld": "dz",
    "fips": "AG"
  },
  "EC": {
    "name": "Ecuador",
    "shortName": "Ecuador",
    "nativeName": "Ecuador",
    "capital": "Quito",
    "continent": "South America",
    "currency": "Dollar",
    "callingCode": "593",
    "timeZoneInCapital": "America/Guayaquil",
    "alpha2": "EC",
    "alpha3": "ECU",
    "numeric": "218",
    "tld": "ec",
    "fips": "EC"
  },
  "EE": {
    "name": "Estonia",
    "shortName": "Estonia",
    "nativeName": "Eesti",
    "capital": "Tallinn",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "372",
    "timeZoneInCapital": "Europe/Tallinn",
    "alpha2": "EE",
    "alpha3": "EST",
    "numeric": "233",
    "tld": "ee",
    "fips": "EN"
  },
  "EG": {
    "name": "Egypt",
    "shortName": "Egypt",
    "nativeName": "مصر‎",
    "capital": "Cairo",
    "continent": "Africa",
    "currency": "Pound",
    "callingCode": "20",
    "timeZoneInCapital": "Africa/Cairo",
    "alpha2": "EG",
    "alpha3": "EGY",
    "numeric": "818",
    "tld": "eg",
    "fips": "EG"
  },
  "EH": {
    "name": "Western Sahara*",
    "shortName": "Western Sahara",
    "nativeName": "الصحراء الغربية",
    "capital": "El-Aaiun",
    "continent": "Africa",
    "currency": "Dirham",
    "callingCode": "212",
    "timeZoneInCapital": "Africa/El_Aaiun",
    "alpha2": "EH",
    "alpha3": "ESH",
    "numeric": "732",
    "tld": "eh",
    "fips": "WI"
  },
  "ER": {
    "name": "Eritrea",
    "shortName": "Eritrea",
    "nativeName": "ኤርትራ",
    "capital": "Asmara",
    "continent": "Africa",
    "currency": "Nakfa",
    "callingCode": "291",
    "timeZoneInCapital": "Africa/Asmara",
    "alpha2": "ER",
    "alpha3": "ERI",
    "numeric": "232",
    "tld": "er",
    "fips": "ER"
  },
  "ES": {
    "name": "Spain",
    "shortName": "Spain",
    "nativeName": "España",
    "capital": "Madrid",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "34",
    "timeZoneInCapital": "Europe/Madrid",
    "alpha2": "ES",
    "alpha3": "ESP",
    "numeric": "724",
    "tld": "es",
    "fips": "SP"
  },
  "ET": {
    "name": "Ethiopia",
    "shortName": "Ethiopia",
    "nativeName": "ኢትዮጵያ",
    "capital": "Addis Ababa",
    "continent": "Africa",
    "currency": "Birr",
    "callingCode": "251",
    "timeZoneInCapital": "Africa/Addis_Ababa",
    "alpha2": "ET",
    "alpha3": "ETH",
    "numeric": "231",
    "tld": "et",
    "fips": "ET"
  },
  "FI": {
    "name": "Finland",
    "shortName": "Finland",
    "nativeName": "Suomi",
    "capital": "Helsinki",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "358",
    "timeZoneInCapital": "Europe/Helsinki",
    "alpha2": "FI",
    "alpha3": "FIN",
    "numeric": "246",
    "tld": "fi",
    "fips": "FI"
  },
  "FJ": {
    "name": "Fiji",
    "shortName": "Fiji",
    "nativeName": "Fiji",
    "capital": "Suva",
    "continent": "Oceania",
    "currency": "Dollar",
    "callingCode": "679",
    "timeZoneInCapital": "Pacific/Fiji",
    "alpha2": "FJ",
    "alpha3": "FJI",
    "numeric": "242",
    "tld": "fj",
    "fips": "FJ"
  },
  "FK": {
    "name": "Falkland Islands (the) [Malvinas]",
    "shortName": "Falkland Islands",
    "nativeName": "Falkland Islands",
    "capital": "Stanley",
    "continent": "South America",
    "currency": "Pound",
    "callingCode": "500",
    "timeZoneInCapital": "Atlantic/Stanley",
    "alpha2": "FK",
    "alpha3": "FLK",
    "numeric": "238",
    "tld": "fk",
    "fips": "FK"
  },
  "FM": {
    "name": "Micronesia (Federated States of)",
    "shortName": "Micronesia",
    "nativeName": "Micronesia",
    "capital": "Palikir",
    "continent": "Oceania",
    "currency": "Dollar",
    "callingCode": "691",
    "timeZoneInCapital": "Pacific/Pohnpei",
    "alpha2": "FM",
    "alpha3": "FSM",
    "numeric": "583",
    "tld": "fm",
    "fips": "FM"
  },
  "FO": {
    "name": "Faroe Islands (the)",
    "shortName": "Faroe Islands",
    "nativeName": "Føroyar",
    "capital": "Torshavn",
    "continent": "Europe",
    "currency": "Krone",
    "callingCode": "298",
    "timeZoneInCapital": "Atlantic/Faroe",
    "alpha2": "FO",
    "alpha3": "FRO",
    "numeric": "234",
    "tld": "fo",
    "fips": "FO"
  },
  "FR": {
    "name": "France",
    "shortName": "France",
    "nativeName": "France",
    "capital": "Paris",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "33",
    "timeZoneInCapital": "Europe/Paris",
    "alpha2": "FR",
    "alpha3": "FRA",
    "numeric": "250",
    "tld": "fr",
    "fips": "FR"
  },
  "GA": {
    "name": "Gabon",
    "shortName": "Gabon",
    "nativeName": "Gabon",
    "capital": "Libreville",
    "continent": "Africa",
    "currency": "Franc",
    "callingCode": "241",
    "timeZoneInCapital": "Africa/Lagos",
    "alpha2": "GA",
    "alpha3": "GAB",
    "numeric": "266",
    "tld": "ga",
    "fips": "GB"
  },
  "GB": {
    "name": "United Kingdom of Great Britain and Northern Ireland (the)",
    "shortName": "UK",
    "nativeName": "United Kingdom",
    "capital": "London",
    "continent": "Europe",
    "currency": "Pound",
    "callingCode": "44",
    "timeZoneInCapital": "Europe/London",
    "alpha2": "GB",
    "alpha3": "GBR",
    "numeric": "826",
    "tld": "uk",
    "fips": "UK"
  },
  "GD": {
    "name": "Grenada",
    "shortName": "Grenada",
    "nativeName": "Grenada",
    "capital": "St. George's",
    "continent": "North America",
    "currency": "Dollar",
    "callingCode": "1-473",
    "timeZoneInCapital": "America/Port_of_Spain",
    "alpha2": "GD",
    "alpha3": "GRD",
    "numeric": "308",
    "tld": "gd",
    "fips": "GJ"
  },
  "GE": {
    "name": "Georgia",
    "shortName": "Georgia",
    "nativeName": "საქართველო",
    "capital": "Tbilisi",
    "continent": "Asia",
    "currency": "Lari",
    "callingCode": "995",
    "timeZoneInCapital": "Asia/Tbilisi",
    "alpha2": "GE",
    "alpha3": "GEO",
    "numeric": "268",
    "tld": "ge",
    "fips": "GG"
  },
  "GF": {
    "name": "French Guiana",
    "shortName": "French Guiana",
    "nativeName": "Guyane française",
    "capital": "Cayenne",
    "continent": "South America",
    "currency": "Euro",
    "callingCode": "594",
    "timeZoneInCapital": "America/Cayenne",
    "alpha2": "GF",
    "alpha3": "GUF",
    "numeric": "254",
    "tld": "gf",
    "fips": "FG"
  },
  "GG": {
    "name": "Guernsey",
    "shortName": "Guernsey",
    "nativeName": "Guernsey",
    "capital": "St Peter Port",
    "continent": "Europe",
    "currency": "Pound",
    "callingCode": "44-1481",
    "timeZoneInCapital": "Europe/London",
    "alpha2": "GG",
    "alpha3": "GGY",
    "numeric": "831",
    "tld": "gg",
    "fips": "GK"
  },
  "GH": {
    "name": "Ghana",
    "shortName": "Ghana",
    "nativeName": "Ghana",
    "capital": "Accra",
    "continent": "Africa",
    "currency": "Cedi",
    "callingCode": "233",
    "timeZoneInCapital": "Africa/Accra",
    "alpha2": "GH",
    "alpha3": "GHA",
    "numeric": "288",
    "tld": "gh",
    "fips": "GH"
  },
  "GI": {
    "name": "Gibraltar",
    "shortName": "Gibraltar",
    "nativeName": "Gibraltar",
    "capital": "Gibraltar",
    "continent": "Europe",
    "currency": "Pound",
    "callingCode": "350",
    "timeZoneInCapital": "Europe/Gibraltar",
    "alpha2": "GI",
    "alpha3": "GIB",
    "numeric": "292",
    "tld": "gi",
    "fips": "GI"
  },
  "GL": {
    "name": "Greenland",
    "shortName": "Greenland",
    "nativeName": "Kalaallit Nunaat",
    "capital": "Nuuk",
    "continent": "North America",
    "currency": "Krone",
    "callingCode": "299",
    "timeZoneInCapital": "America/Godthab",
    "alpha2": "GL",
    "alpha3": "GRL",
    "numeric": "304",
    "tld": "gl",
    "fips": "GL"
  },
  "GM": {
    "name": "Gambia (the)",
    "shortName": "Gambia",
    "nativeName": "Gambia",
    "capital": "Banjul",
    "continent": "Africa",
    "currency": "Dalasi",
    "callingCode": "220",
    "timeZoneInCapital": "Africa/Abidjan",
    "alpha2": "GM",
    "alpha3": "GMB",
    "numeric": "270",
    "tld": "gm",
    "fips": "GA"
  },
  "GN": {
    "name": "Guinea",
    "shortName": "Guinea",
    "nativeName": "Guinée",
    "capital": "Conakry",
    "continent": "Africa",
    "currency": "Franc",
    "callingCode": "224",
    "timeZoneInCapital": "Africa/Abidjan",
    "alpha2": "GN",
    "alpha3": "GIN",
    "numeric": "324",
    "tld": "gn",
    "fips": "GV"
  },
  "GP": {
    "name": "Guadeloupe",
    "shortName": "Guadeloupe",
    "nativeName": "Guadeloupe",
    "capital": "Basse-Terre",
    "continent": "North America",
    "currency": "Euro",
    "callingCode": "590",
    "timeZoneInCapital": "America/Guadeloupe",
    "alpha2": "GP",
    "alpha3": "GLP",
    "numeric": "312",
    "tld": "gp",
    "fips": "GP"
  },
  "GQ": {
    "name": "Equatorial Guinea",
    "shortName": "Equatorial Guinea",
    "nativeName": "Guinea Ecuatorial",
    "capital": "Malabo",
    "continent": "Africa",
    "currency": "Franc",
    "callingCode": "240",
    "timeZoneInCapital": "Africa/Lagos",
    "alpha2": "GQ",
    "alpha3": "GNQ",
    "numeric": "226",
    "tld": "gq",
    "fips": "EK"
  },
  "GR": {
    "name": "Greece",
    "shortName": "Greece",
    "nativeName": "Ελλάδα",
    "capital": "Athens",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "30",
    "timeZoneInCapital": "Europe/Athens",
    "alpha2": "GR",
    "alpha3": "GRC",
    "numeric": "300",
    "tld": "gr",
    "fips": "GR"
  },
  "GS": {
    "name": "South Georgia and the South Sandwich Islands",
    "shortName": "South Georgia And Sandwich Isl.",
    "nativeName": "South Georgia",
    "capital": "King Edward Point",
    "continent": "South America",
    "currency": "Pound",
    "callingCode": "500",
    "timeZoneInCapital": "Atlantic/South_Georgia",
    "alpha2": "GS",
    "alpha3": "SGS",
    "numeric": "239",
    "tld": "gs",
    "fips": "SX"
  },
  "GT": {
    "name": "Guatemala",
    "shortName": "Guatemala",
    "nativeName": "Guatemala",
    "capital": "Guatemala City",
    "continent": "North America",
    "currency": "Quetzal",
    "callingCode": "502",
    "timeZoneInCapital": "America/Guatemala",
    "alpha2": "GT",
    "alpha3": "GTM",
    "numeric": "320",
    "tld": "gt",
    "fips": "GT"
  },
  "GU": {
    "name": "Guam",
    "shortName": "Guam",
    "nativeName": "Guam",
    "capital": "Hagatna",
    "continent": "Oceania",
    "currency": "Dollar",
    "callingCode": "1-671",
    "timeZoneInCapital": "Pacific/Guam",
    "alpha2": "GU",
    "alpha3": "GUM",
    "numeric": "316",
    "tld": "gu",
    "fips": "GQ"
  },
  "GW": {
    "name": "Guinea-Bissau",
    "shortName": "Guinea-Bissau",
    "nativeName": "Guiné-Bissau",
    "capital": "Bissau",
    "continent": "Africa",
    "currency": "Franc",
    "callingCode": "245",
    "timeZoneInCapital": "Africa/Bissau",
    "alpha2": "GW",
    "alpha3": "GNB",
    "numeric": "624",
    "tld": "gw",
    "fips": "PU"
  },
  "GY": {
    "name": "Guyana",
    "shortName": "Guyana",
    "nativeName": "Guyana",
    "capital": "Georgetown",
    "continent": "South America",
    "currency": "Dollar",
    "callingCode": "592",
    "timeZoneInCapital": "America/Guyana",
    "alpha2": "GY",
    "alpha3": "GUY",
    "numeric": "328",
    "tld": "gy",
    "fips": "GY"
  },
  "HK": {
    "name": "Hong Kong",
    "shortName": "Hong Kong",
    "nativeName": "香港",
    "capital": "Hong Kong",
    "continent": "Asia",
    "currency": "Dollar",
    "callingCode": "852",
    "timeZoneInCapital": "Asia/Hong_Kong",
    "alpha2": "HK",
    "alpha3": "HKG",
    "numeric": "344",
    "tld": "hk",
    "fips": "HK"
  },
  "HM": {
    "name": "Heard Island and McDonald Islands",
    "shortName": "Heard Island & Mcdonald Islands",
    "nativeName": "Heard Island and McDonald Islands",
    "capital": "",
    "continent": "Oceania",
    "currency": "Dollar",
    "callingCode": "",
    "timeZoneInCapital": "",
    "alpha2": "HM",
    "alpha3": "HMD",
    "numeric": "334",
    "tld": "hm",
    "fips": "HM"
  },
  "HN": {
    "name": "Honduras",
    "shortName": "Honduras",
    "nativeName": "Honduras",
    "capital": "Tegucigalpa",
    "continent": "North America",
    "currency": "Lempira",
    "callingCode": "504",
    "timeZoneInCapital": "America/Tegucigalpa",
    "alpha2": "HN",
    "alpha3": "HND",
    "numeric": "340",
    "tld": "hn",
    "fips": "HO"
  },
  "HR": {
    "name": "Croatia",
    "shortName": "Croatia",
    "nativeName": "Hrvatska",
    "capital": "Zagreb",
    "continent": "Europe",
    "currency": "Kuna",
    "callingCode": "385",
    "timeZoneInCapital": "Europe/Belgrade",
    "alpha2": "HR",
    "alpha3": "HRV",
    "numeric": "191",
    "tld": "hr",
    "fips": "HR"
  },
  "HT": {
    "name": "Haiti",
    "shortName": "Haiti",
    "nativeName": "Haïti",
    "capital": "Port-au-Prince",
    "continent": "North America",
    "currency": "Gourde",
    "callingCode": "509",
    "timeZoneInCapital": "America/Port-au-Prince",
    "alpha2": "HT",
    "alpha3": "HTI",
    "numeric": "332",
    "tld": "ht",
    "fips": "HA"
  },
  "HU": {
    "name": "Hungary",
    "shortName": "Hungary",
    "nativeName": "Magyarország",
    "capital": "Budapest",
    "continent": "Europe",
    "currency": "Forint",
    "callingCode": "36",
    "timeZoneInCapital": "Europe/Budapest",
    "alpha2": "HU",
    "alpha3": "HUN",
    "numeric": "348",
    "tld": "hu",
    "fips": "HU"
  },
  "ID": {
    "name": "Indonesia",
    "shortName": "Indonesia",
    "nativeName": "Indonesia",
    "capital": "Jakarta",
    "continent": "Asia",
    "currency": "Rupiah",
    "callingCode": "62",
    "timeZoneInCapital": "Asia/Jakarta",
    "alpha2": "ID",
    "alpha3": "IDN",
    "numeric": "360",
    "tld": "id",
    "fips": "ID"
  },
  "IE": {
    "name": "Ireland",
    "shortName": "Ireland",
    "nativeName": "Éire",
    "capital": "Dublin",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "353",
    "timeZoneInCapital": "Europe/Dublin",
    "alpha2": "IE",
    "alpha3": "IRL",
    "numeric": "372",
    "tld": "ie",
    "fips": "EI"
  },
  "IL": {
    "name": "Israel",
    "shortName": "Israel",
    "nativeName": "ישראל",
    "capital": "Jerusalem",
    "continent": "Asia",
    "currency": "Shekel",
    "callingCode": "972",
    "timeZoneInCapital": "Asia/Jerusalem",
    "alpha2": "IL",
    "alpha3": "ISR",
    "numeric": "376",
    "tld": "il",
    "fips": "IS"
  },
  "IM": {
    "name": "Isle of Man",
    "shortName": "Isle of Man",
    "nativeName": "Isle of Man",
    "capital": "Douglas, Isle of Man",
    "continent": "Europe",
    "currency": "Pound",
    "callingCode": "44-1624",
    "timeZoneInCapital": "Europe/London",
    "alpha2": "IM",
    "alpha3": "IMN",
    "numeric": "833",
    "tld": "im",
    "fips": "IM"
  },
  "IN": {
    "name": "India",
    "shortName": "India",
    "nativeName": "भारत",
    "capital": "New Delhi",
    "continent": "Asia",
    "currency": "Rupee",
    "callingCode": "91",
    "timeZoneInCapital": "Asia/Kolkata",
    "alpha2": "IN",
    "alpha3": "IND",
    "numeric": "356",
    "tld": "in",
    "fips": "IN"
  },
  "IO": {
    "name": "British Indian Ocean Territory (the)",
    "shortName": "British Indian Ocean Territory",
    "nativeName": "British Indian Ocean Territory",
    "capital": "Diego Garcia",
    "continent": "Asia",
    "currency": "Dollar",
    "callingCode": "246",
    "timeZoneInCapital": "Indian/Chagos",
    "alpha2": "IO",
    "alpha3": "IOT",
    "numeric": "86",
    "tld": "io",
    "fips": "IO"
  },
  "IQ": {
    "name": "Iraq",
    "shortName": "Iraq",
    "nativeName": "العراق",
    "capital": "Baghdad",
    "continent": "Asia",
    "currency": "Dinar",
    "callingCode": "964",
    "timeZoneInCapital": "Asia/Baghdad",
    "alpha2": "IQ",
    "alpha3": "IRQ",
    "numeric": "368",
    "tld": "iq",
    "fips": "IZ"
  },
  "IR": {
    "name": "Iran (Islamic Republic of)",
    "shortName": "Iran",
    "nativeName": "ایران",
    "capital": "Tehran",
    "continent": "Asia",
    "currency": "Rial",
    "callingCode": "98",
    "timeZoneInCapital": "Asia/Tehran",
    "alpha2": "IR",
    "alpha3": "IRN",
    "numeric": "364",
    "tld": "ir",
    "fips": "IR"
  },
  "IS": {
    "name": "Iceland",
    "shortName": "Iceland",
    "nativeName": "Ísland",
    "capital": "Reykjavik",
    "continent": "Europe",
    "currency": "Krona",
    "callingCode": "354",
    "timeZoneInCapital": "Atlantic/Reykjavik",
    "alpha2": "IS",
    "alpha3": "ISL",
    "numeric": "352",
    "tld": "is",
    "fips": "IC"
  },
  "IT": {
    "name": "Italy",
    "shortName": "Italy",
    "nativeName": "Italia",
    "capital": "Rome",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "39",
    "timeZoneInCapital": "Europe/Rome",
    "alpha2": "IT",
    "alpha3": "ITA",
    "numeric": "380",
    "tld": "it",
    "fips": "IT"
  },
  "JE": {
    "name": "Jersey",
    "shortName": "Jersey",
    "nativeName": "Jersey",
    "capital": "Saint Helier",
    "continent": "Europe",
    "currency": "Pound",
    "callingCode": "44-1534",
    "timeZoneInCapital": "Europe/London",
    "alpha2": "JE",
    "alpha3": "JEY",
    "numeric": "832",
    "tld": "je",
    "fips": "JE"
  },
  "JM": {
    "name": "Jamaica",
    "shortName": "Jamaica",
    "nativeName": "Jamaica",
    "capital": "Kingston",
    "continent": "North America",
    "currency": "Dollar",
    "callingCode": "1-876",
    "timeZoneInCapital": "America/Jamaica",
    "alpha2": "JM",
    "alpha3": "JAM",
    "numeric": "388",
    "tld": "jm",
    "fips": "JM"
  },
  "JO": {
    "name": "Jordan",
    "shortName": "Jordan",
    "nativeName": "الأردن",
    "capital": "Amman",
    "continent": "Asia",
    "currency": "Dinar",
    "callingCode": "962",
    "timeZoneInCapital": "Asia/Amman",
    "alpha2": "JO",
    "alpha3": "JOR",
    "numeric": "400",
    "tld": "jo",
    "fips": "JO"
  },
  "JP": {
    "name": "Japan",
    "shortName": "Japan",
    "nativeName": "日本",
    "capital": "Tokyo",
    "continent": "Asia",
    "currency": "Yen",
    "callingCode": "81",
    "timeZoneInCapital": "Asia/Tokyo",
    "alpha2": "JP",
    "alpha3": "JPN",
    "numeric": "392",
    "tld": "jp",
    "fips": "JA"
  },
  "KE": {
    "name": "Kenya",
    "shortName": "Kenya",
    "nativeName": "Kenya",
    "capital": "Nairobi",
    "continent": "Africa",
    "currency": "Shilling",
    "callingCode": "254",
    "timeZoneInCapital": "Africa/Nairobi",
    "alpha2": "KE",
    "alpha3": "KEN",
    "numeric": "404",
    "tld": "ke",
    "fips": "KE"
  },
  "KG": {
    "name": "Kyrgyzstan",
    "shortName": "Kyrgyzstan",
    "nativeName": "Кыргызстан",
    "capital": "Bishkek",
    "continent": "Asia",
    "currency": "Som",
    "callingCode": "996",
    "timeZoneInCapital": "Asia/Bishkek",
    "alpha2": "KG",
    "alpha3": "KGZ",
    "numeric": "417",
    "tld": "kg",
    "fips": "KG"
  },
  "KH": {
    "name": "Cambodia",
    "shortName": "Cambodia",
    "nativeName": "Cambodia",
    "capital": "Phnom Penh",
    "continent": "Asia",
    "currency": "Riels",
    "callingCode": "855",
    "timeZoneInCapital": "Asia/Phnom_Penh",
    "alpha2": "KH",
    "alpha3": "KHM",
    "numeric": "116",
    "tld": "kh",
    "fips": "CB"
  },
  "KI": {
    "name": "Kiribati",
    "shortName": "Kiribati",
    "nativeName": "Kiribati",
    "capital": "Tarawa",
    "continent": "Oceania",
    "currency": "Dollar",
    "callingCode": "686",
    "timeZoneInCapital": "Pacific/Tarawa",
    "alpha2": "KI",
    "alpha3": "KIR",
    "numeric": "296",
    "tld": "ki",
    "fips": "KR"
  },
  "KM": {
    "name": "Comoros (the)",
    "shortName": "Comoros",
    "nativeName": "Komori",
    "capital": "Moroni",
    "continent": "Africa",
    "currency": "Franc",
    "callingCode": "269",
    "timeZoneInCapital": "Indian/Comoro",
    "alpha2": "KM",
    "alpha3": "COM",
    "numeric": "174",
    "tld": "km",
    "fips": "CN"
  },
  "KN": {
    "name": "Saint Kitts and Nevis",
    "shortName": "Saint Kitts and Nevis",
    "nativeName": "Saint Kitts and Nevis",
    "capital": "Basseterre",
    "continent": "North America",
    "currency": "Dollar",
    "callingCode": "1-869",
    "timeZoneInCapital": "America/Port_of_Spain",
    "alpha2": "KN",
    "alpha3": "KNA",
    "numeric": "659",
    "tld": "kn",
    "fips": "SC"
  },
  "KP": {
    "name": "Korea (the Democratic People's Republic of)",
    "shortName": "North Korea",
    "nativeName": "조선민주주의인민공화국",
    "capital": "Pyongyang",
    "continent": "Asia",
    "currency": "Won",
    "callingCode": "850",
    "timeZoneInCapital": "Asia/Pyongyang",
    "alpha2": "KP",
    "alpha3": "PRK",
    "numeric": "408",
    "tld": "kp",
    "fips": "KN"
  },
  "KR": {
    "name": "Korea (the Republic of)",
    "shortName": "Korea",
    "nativeName": "대한민국",
    "capital": "Seoul",
    "continent": "Asia",
    "currency": "Won",
    "callingCode": "82",
    "timeZoneInCapital": "Asia/Seoul",
    "alpha2": "KR",
    "alpha3": "KOR",
    "numeric": "410",
    "tld": "kr",
    "fips": "KS"
  },
  "KW": {
    "name": "Kuwait",
    "shortName": "Kuwait",
    "nativeName": "الكويت",
    "capital": "Kuwait City",
    "continent": "Asia",
    "currency": "Dinar",
    "callingCode": "965",
    "timeZoneInCapital": "Asia/Kuwait",
    "alpha2": "KW",
    "alpha3": "KWT",
    "numeric": "414",
    "tld": "kw",
    "fips": "KU"
  },
  "KY": {
    "name": "Cayman Islands (the)",
    "shortName": "Cayman Islands",
    "nativeName": "Cayman Islands",
    "capital": "George Town",
    "continent": "North America",
    "currency": "Dollar",
    "callingCode": "1-345",
    "timeZoneInCapital": "America/Cayman",
    "alpha2": "KY",
    "alpha3": "CYM",
    "numeric": "136",
    "tld": "ky",
    "fips": "CJ"
  },
  "KZ": {
    "name": "Kazakhstan",
    "shortName": "Kazakhstan",
    "nativeName": "Қазақстан",
    "capital": "Astana",
    "continent": "Asia",
    "currency": "Tenge",
    "callingCode": "7",
    "timeZoneInCapital": "Asia/Almaty",
    "alpha2": "KZ",
    "alpha3": "KAZ",
    "numeric": "398",
    "tld": "kz",
    "fips": "KZ"
  },
  "LA": {
    "name": "Lao People's Democratic Republic (the)",
    "shortName": "Laos",
    "nativeName": "ສປປລາວ",
    "capital": "Vientiane",
    "continent": "Asia",
    "currency": "Kip",
    "callingCode": "856",
    "timeZoneInCapital": "Asia/Vientiane",
    "alpha2": "LA",
    "alpha3": "LAO",
    "numeric": "418",
    "tld": "la",
    "fips": "LA"
  },
  "LB": {
    "name": "Lebanon",
    "shortName": "Lebanon",
    "nativeName": "لبنان",
    "capital": "Beirut",
    "continent": "Asia",
    "currency": "Pound",
    "callingCode": "961",
    "timeZoneInCapital": "Asia/Beirut",
    "alpha2": "LB",
    "alpha3": "LBN",
    "numeric": "422",
    "tld": "lb",
    "fips": "LE"
  },
  "LC": {
    "name": "Saint Lucia",
    "shortName": "Saint Lucia",
    "nativeName": "Saint Lucia",
    "capital": "Castries",
    "continent": "North America",
    "currency": "Dollar",
    "callingCode": "1-758",
    "timeZoneInCapital": "America/Port_of_Spain",
    "alpha2": "LC",
    "alpha3": "LCA",
    "numeric": "662",
    "tld": "lc",
    "fips": "ST"
  },
  "LI": {
    "name": "Liechtenstein",
    "shortName": "Liechtenstein",
    "nativeName": "Liechtenstein",
    "capital": "Vaduz",
    "continent": "Europe",
    "currency": "Franc",
    "callingCode": "423",
    "timeZoneInCapital": "Europe/Zurich",
    "alpha2": "LI",
    "alpha3": "LIE",
    "numeric": "438",
    "tld": "li",
    "fips": "LS"
  },
  "LK": {
    "name": "Sri Lanka",
    "shortName": "Sri Lanka",
    "nativeName": "Sri Lanka",
    "capital": "Colombo",
    "continent": "Asia",
    "currency": "Rupee",
    "callingCode": "94",
    "timeZoneInCapital": "Asia/Colombo",
    "alpha2": "LK",
    "alpha3": "LKA",
    "numeric": "144",
    "tld": "lk",
    "fips": "CE"
  },
  "LR": {
    "name": "Liberia",
    "shortName": "Liberia",
    "nativeName": "Liberia",
    "capital": "Monrovia",
    "continent": "Africa",
    "currency": "Dollar",
    "callingCode": "231",
    "timeZoneInCapital": "Africa/Monrovia",
    "alpha2": "LR",
    "alpha3": "LBR",
    "numeric": "430",
    "tld": "lr",
    "fips": "LI"
  },
  "LS": {
    "name": "Lesotho",
    "shortName": "Lesotho",
    "nativeName": "Lesotho",
    "capital": "Maseru",
    "continent": "Africa",
    "currency": "Loti",
    "callingCode": "266",
    "timeZoneInCapital": "Africa/Johannesburg",
    "alpha2": "LS",
    "alpha3": "LSO",
    "numeric": "426",
    "tld": "ls",
    "fips": "LT"
  },
  "LT": {
    "name": "Lithuania",
    "shortName": "Lithuania",
    "nativeName": "Lietuva",
    "capital": "Vilnius",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "370",
    "timeZoneInCapital": "Europe/Vilnius",
    "alpha2": "LT",
    "alpha3": "LTU",
    "numeric": "440",
    "tld": "lt",
    "fips": "LH"
  },
  "LU": {
    "name": "Luxembourg",
    "shortName": "Luxembourg",
    "nativeName": "Luxembourg",
    "capital": "Luxembourg",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "352",
    "timeZoneInCapital": "Europe/Luxembourg",
    "alpha2": "LU",
    "alpha3": "LUX",
    "numeric": "442",
    "tld": "lu",
    "fips": "LU"
  },
  "LV": {
    "name": "Latvia",
    "shortName": "Latvia",
    "nativeName": "Latvija",
    "capital": "Riga",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "371",
    "timeZoneInCapital": "Europe/Riga",
    "alpha2": "LV",
    "alpha3": "LVA",
    "numeric": "428",
    "tld": "lv",
    "fips": "LG"
  },
  "LY": {
    "name": "Libya",
    "shortName": "Libya",
    "nativeName": "‏ليبيا",
    "capital": "Tripolis",
    "continent": "Africa",
    "currency": "Dinar",
    "callingCode": "218",
    "timeZoneInCapital": "Africa/Tripoli",
    "alpha2": "LY",
    "alpha3": "LBY",
    "numeric": "434",
    "tld": "ly",
    "fips": "LY"
  },
  "MA": {
    "name": "Morocco",
    "shortName": "Morocco",
    "nativeName": "المغرب",
    "capital": "Rabat",
    "continent": "Africa",
    "currency": "Dirham",
    "callingCode": "212",
    "timeZoneInCapital": "Africa/Casablanca",
    "alpha2": "MA",
    "alpha3": "MAR",
    "numeric": "504",
    "tld": "ma",
    "fips": "MO"
  },
  "MC": {
    "name": "Monaco",
    "shortName": "Monaco",
    "nativeName": "Monaco",
    "capital": "Monaco",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "377",
    "timeZoneInCapital": "Europe/Monaco",
    "alpha2": "MC",
    "alpha3": "MCO",
    "numeric": "492",
    "tld": "mc",
    "fips": "MN"
  },
  "MD": {
    "name": "Moldova (the Republic of)",
    "shortName": "Moldova",
    "nativeName": "Moldova",
    "capital": "Chisinau",
    "continent": "Europe",
    "currency": "Leu",
    "callingCode": "373",
    "timeZoneInCapital": "Europe/Chisinau",
    "alpha2": "MD",
    "alpha3": "MDA",
    "numeric": "498",
    "tld": "md",
    "fips": "MD"
  },
  "ME": {
    "name": "Montenegro",
    "shortName": "Montenegro",
    "nativeName": "Црна Гора",
    "capital": "Podgorica",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "382",
    "timeZoneInCapital": "Europe/Belgrade",
    "alpha2": "ME",
    "alpha3": "MNE",
    "numeric": "499",
    "tld": "me",
    "fips": "MJ"
  },
  "MF": {
    "name": "Saint Martin (French part)",
    "shortName": "Saint Martin",
    "nativeName": "Saint-Martin",
    "capital": "Marigot",
    "continent": "North America",
    "currency": "Euro",
    "callingCode": "590",
    "timeZoneInCapital": "America/Port_of_Spain",
    "alpha2": "MF",
    "alpha3": "MAF",
    "numeric": "663",
    "tld": "gp",
    "fips": "RN"
  },
  "MG": {
    "name": "Madagascar",
    "shortName": "Madagascar",
    "nativeName": "Madagasikara",
    "capital": "Antananarivo",
    "continent": "Africa",
    "currency": "Ariary",
    "callingCode": "261",
    "timeZoneInCapital": "Indian/Antananarivo",
    "alpha2": "MG",
    "alpha3": "MDG",
    "numeric": "450",
    "tld": "mg",
    "fips": "MA"
  },
  "MH": {
    "name": "Marshall Islands (the)",
    "shortName": "Marshall Islands",
    "nativeName": "M̧ajeļ",
    "capital": "Majuro",
    "continent": "Oceania",
    "currency": "Dollar",
    "callingCode": "692",
    "timeZoneInCapital": "Pacific/Majuro",
    "alpha2": "MH",
    "alpha3": "MHL",
    "numeric": "584",
    "tld": "mh",
    "fips": "RM"
  },
  "MK": {
    "name": "North Macedonia",
    "shortName": "Macedonia",
    "nativeName": "Македонија",
    "capital": "Skopje",
    "continent": "Europe",
    "currency": "Denar",
    "callingCode": "389",
    "timeZoneInCapital": "Europe/Belgrade",
    "alpha2": "MK",
    "alpha3": "MKD",
    "numeric": "807",
    "tld": "mk",
    "fips": "MK"
  },
  "ML": {
    "name": "Mali",
    "shortName": "Mali",
    "nativeName": "Mali",
    "capital": "Bamako",
    "continent": "Africa",
    "currency": "Franc",
    "callingCode": "223",
    "timeZoneInCapital": "Africa/Abidjan",
    "alpha2": "ML",
    "alpha3": "MLI",
    "numeric": "466",
    "tld": "ml",
    "fips": "ML"
  },
  "MM": {
    "name": "Myanmar",
    "shortName": "Myanmar",
    "nativeName": "Myanmar",
    "capital": "Nay Pyi Taw",
    "continent": "Asia",
    "currency": "Kyat",
    "callingCode": "95",
    "timeZoneInCapital": "Asia/Rangoon",
    "alpha2": "MM",
    "alpha3": "MMR",
    "numeric": "104",
    "tld": "mm",
    "fips": "BM"
  },
  "MN": {
    "name": "Mongolia",
    "shortName": "Mongolia",
    "nativeName": "Монгол улс",
    "capital": "Ulan Bator",
    "continent": "Asia",
    "currency": "Tugrik",
    "callingCode": "976",
    "timeZoneInCapital": "Asia/Ulaanbaatar",
    "alpha2": "MN",
    "alpha3": "MNG",
    "numeric": "496",
    "tld": "mn",
    "fips": "MG"
  },
  "MO": {
    "name": "Macao",
    "shortName": "Macau",
    "nativeName": "澳門",
    "capital": "Macao",
    "continent": "Asia",
    "currency": "Pataca",
    "callingCode": "853",
    "timeZoneInCapital": "Asia/Macau",
    "alpha2": "MO",
    "alpha3": "MAC",
    "numeric": "446",
    "tld": "mo",
    "fips": "MC"
  },
  "MP": {
    "name": "Northern Mariana Islands (the)",
    "shortName": "Northern Mariana Islands",
    "nativeName": "Northern Mariana Islands",
    "capital": "Saipan",
    "continent": "Oceania",
    "currency": "Dollar",
    "callingCode": "1-670",
    "timeZoneInCapital": "Pacific/Saipan",
    "alpha2": "MP",
    "alpha3": "MNP",
    "numeric": "580",
    "tld": "mp",
    "fips": "CQ"
  },
  "MQ": {
    "name": "Martinique",
    "shortName": "Martinique",
    "nativeName": "Martinique",
    "capital": "Fort-de-France",
    "continent": "North America",
    "currency": "Euro",
    "callingCode": "596",
    "timeZoneInCapital": "America/Martinique",
    "alpha2": "MQ",
    "alpha3": "MTQ",
    "numeric": "474",
    "tld": "mq",
    "fips": "MB"
  },
  "MR": {
    "name": "Mauritania",
    "shortName": "Mauritania",
    "nativeName": "موريتانيا",
    "capital": "Nouakchott",
    "continent": "Africa",
    "currency": "Ouguiya",
    "callingCode": "222",
    "timeZoneInCapital": "Africa/Abidjan",
    "alpha2": "MR",
    "alpha3": "MRT",
    "numeric": "478",
    "tld": "mr",
    "fips": "MR"
  },
  "MS": {
    "name": "Montserrat",
    "shortName": "Montserrat",
    "nativeName": "Montserrat",
    "capital": "Plymouth",
    "continent": "North America",
    "currency": "Dollar",
    "callingCode": "1-664",
    "timeZoneInCapital": "America/Port_of_Spain",
    "alpha2": "MS",
    "alpha3": "MSR",
    "numeric": "500",
    "tld": "ms",
    "fips": "MH"
  },
  "MT": {
    "name": "Malta",
    "shortName": "Malta",
    "nativeName": "Malta",
    "capital": "Valletta",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "356",
    "timeZoneInCapital": "Europe/Malta",
    "alpha2": "MT",
    "alpha3": "MLT",
    "numeric": "470",
    "tld": "mt",
    "fips": "MT"
  },
  "MU": {
    "name": "Mauritius",
    "shortName": "Mauritius",
    "nativeName": "Maurice",
    "capital": "Port Louis",
    "continent": "Africa",
    "currency": "Rupee",
    "callingCode": "230",
    "timeZoneInCapital": "Indian/Mauritius",
    "alpha2": "MU",
    "alpha3": "MUS",
    "numeric": "480",
    "tld": "mu",
    "fips": "MP"
  },
  "MV": {
    "name": "Maldives",
    "shortName": "Maldives",
    "nativeName": "Maldives",
    "capital": "Male",
    "continent": "Asia",
    "currency": "Rufiyaa",
    "callingCode": "960",
    "timeZoneInCapital": "Indian/Maldives",
    "alpha2": "MV",
    "alpha3": "MDV",
    "numeric": "462",
    "tld": "mv",
    "fips": "MV"
  },
  "MW": {
    "name": "Malawi",
    "shortName": "Malawi",
    "nativeName": "Malawi",
    "capital": "Lilongwe",
    "continent": "Africa",
    "currency": "Kwacha",
    "callingCode": "265",
    "timeZoneInCapital": "Africa/Maputo",
    "alpha2": "MW",
    "alpha3": "MWI",
    "numeric": "454",
    "tld": "mw",
    "fips": "MI"
  },
  "MX": {
    "name": "Mexico",
    "shortName": "Mexico",
    "nativeName": "México",
    "capital": "Mexico City",
    "continent": "North America",
    "currency": "Peso",
    "callingCode": "52",
    "timeZoneInCapital": "America/Mexico_City",
    "alpha2": "MX",
    "alpha3": "MEX",
    "numeric": "484",
    "tld": "mx",
    "fips": "MX"
  },
  "MY": {
    "name": "Malaysia",
    "shortName": "Malaysia",
    "nativeName": "Malaysia",
    "capital": "Kuala Lumpur",
    "continent": "Asia",
    "currency": "Ringgit",
    "callingCode": "60",
    "timeZoneInCapital": "Asia/Kuala_Lumpur",
    "alpha2": "MY",
    "alpha3": "MYS",
    "numeric": "458",
    "tld": "my",
    "fips": "MY"
  },
  "MZ": {
    "name": "Mozambique",
    "shortName": "Mozambique",
    "nativeName": "Moçambique",
    "capital": "Maputo",
    "continent": "Africa",
    "currency": "Metical",
    "callingCode": "258",
    "timeZoneInCapital": "Africa/Maputo",
    "alpha2": "MZ",
    "alpha3": "MOZ",
    "numeric": "508",
    "tld": "mz",
    "fips": "MZ"
  },
  "NA": {
    "name": "Namibia",
    "shortName": "Namibia",
    "nativeName": "Namibia",
    "capital": "Windhoek",
    "continent": "Africa",
    "currency": "Dollar",
    "callingCode": "264",
    "timeZoneInCapital": "Africa/Windhoek",
    "alpha2": "NA",
    "alpha3": "NAM",
    "numeric": "516",
    "tld": "na",
    "fips": "WA"
  },
  "NC": {
    "name": "New Caledonia",
    "shortName": "New Caledonia",
    "nativeName": "Nouvelle-Calédonie",
    "capital": "Noumea",
    "continent": "Oceania",
    "currency": "Franc",
    "callingCode": "687",
    "timeZoneInCapital": "Pacific/Noumea",
    "alpha2": "NC",
    "alpha3": "NCL",
    "numeric": "540",
    "tld": "nc",
    "fips": "NC"
  },
  "NE": {
    "name": "Niger (the)",
    "shortName": "Niger",
    "nativeName": "Niger",
    "capital": "Niamey",
    "continent": "Africa",
    "currency": "Franc",
    "callingCode": "227",
    "timeZoneInCapital": "Africa/Lagos",
    "alpha2": "NE",
    "alpha3": "NER",
    "numeric": "562",
    "tld": "ne",
    "fips": "NG"
  },
  "NF": {
    "name": "Norfolk Island",
    "shortName": "Norfolk Island",
    "nativeName": "Norfolk Island",
    "capital": "Kingston",
    "continent": "Oceania",
    "currency": "Dollar",
    "callingCode": "672",
    "timeZoneInCapital": "Pacific/Norfolk",
    "alpha2": "NF",
    "alpha3": "NFK",
    "numeric": "574",
    "tld": "nf",
    "fips": "NF"
  },
  "NG": {
    "name": "Nigeria",
    "shortName": "Nigeria",
    "nativeName": "Nigeria",
    "capital": "Abuja",
    "continent": "Africa",
    "currency": "Naira",
    "callingCode": "234",
    "timeZoneInCapital": "Africa/Lagos",
    "alpha2": "NG",
    "alpha3": "NGA",
    "numeric": "566",
    "tld": "ng",
    "fips": "NI"
  },
  "NI": {
    "name": "Nicaragua",
    "shortName": "Nicaragua",
    "nativeName": "Nicaragua",
    "capital": "Managua",
    "continent": "North America",
    "currency": "Cordoba",
    "callingCode": "505",
    "timeZoneInCapital": "America/Managua",
    "alpha2": "NI",
    "alpha3": "NIC",
    "numeric": "558",
    "tld": "ni",
    "fips": "NU"
  },
  "NL": {
    "name": "Netherlands (the)",
    "shortName": "Netherlands",
    "nativeName": "Nederland",
    "capital": "Amsterdam",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "31",
    "timeZoneInCapital": "Europe/Amsterdam",
    "alpha2": "NL",
    "alpha3": "NLD",
    "numeric": "528",
    "tld": "nl",
    "fips": "NL"
  },
  "NO": {
    "name": "Norway",
    "shortName": "Norway",
    "nativeName": "Norge",
    "capital": "Oslo",
    "continent": "Europe",
    "currency": "Krone",
    "callingCode": "47",
    "timeZoneInCapital": "Europe/Oslo",
    "alpha2": "NO",
    "alpha3": "NOR",
    "numeric": "578",
    "tld": "no",
    "fips": "NO"
  },
  "NP": {
    "name": "Nepal",
    "shortName": "Nepal",
    "nativeName": "नपल",
    "capital": "Kathmandu",
    "continent": "Asia",
    "currency": "Rupee",
    "callingCode": "977",
    "timeZoneInCapital": "Asia/Kathmandu",
    "alpha2": "NP",
    "alpha3": "NPL",
    "numeric": "524",
    "tld": "np",
    "fips": "NP"
  },
  "NR": {
    "name": "Nauru",
    "shortName": "Nauru",
    "nativeName": "Nauru",
    "capital": "Yaren",
    "continent": "Oceania",
    "currency": "Dollar",
    "callingCode": "674",
    "timeZoneInCapital": "Pacific/Nauru",
    "alpha2": "NR",
    "alpha3": "NRU",
    "numeric": "520",
    "tld": "nr",
    "fips": "NR"
  },
  "NU": {
    "name": "Niue",
    "shortName": "Niue",
    "nativeName": "Niuē",
    "capital": "Alofi",
    "continent": "Oceania",
    "currency": "Dollar",
    "callingCode": "683",
    "timeZoneInCapital": "Pacific/Niue",
    "alpha2": "NU",
    "alpha3": "NIU",
    "numeric": "570",
    "tld": "nu",
    "fips": "NE"
  },
  "NZ": {
    "name": "New Zealand",
    "shortName": "New Zealand",
    "nativeName": "New Zealand",
    "capital": "Wellington",
    "continent": "Oceania",
    "currency": "Dollar",
    "callingCode": "64",
    "timeZoneInCapital": "Pacific/Auckland",
    "alpha2": "NZ",
    "alpha3": "NZL",
    "numeric": "554",
    "tld": "nz",
    "fips": "NZ"
  },
  "OM": {
    "name": "Oman",
    "shortName": "Oman",
    "nativeName": "عمان",
    "capital": "Muscat",
    "continent": "Asia",
    "currency": "Rial",
    "callingCode": "968",
    "timeZoneInCapital": "Asia/Muscat",
    "alpha2": "OM",
    "alpha3": "OMN",
    "numeric": "512",
    "tld": "om",
    "fips": "MU"
  },
  "PA": {
    "name": "Panama",
    "shortName": "Panama",
    "nativeName": "Panamá",
    "capital": "Panama City",
    "continent": "North America",
    "currency": "Balboa",
    "callingCode": "507",
    "timeZoneInCapital": "America/Panama",
    "alpha2": "PA",
    "alpha3": "PAN",
    "numeric": "591",
    "tld": "pa",
    "fips": "PM"
  },
  "PE": {
    "name": "Peru",
    "shortName": "Peru",
    "nativeName": "Perú",
    "capital": "Lima",
    "continent": "South America",
    "currency": "Sol",
    "callingCode": "51",
    "timeZoneInCapital": "America/Lima",
    "alpha2": "PE",
    "alpha3": "PER",
    "numeric": "604",
    "tld": "pe",
    "fips": "PE"
  },
  "PF": {
    "name": "French Polynesia",
    "shortName": "French Polynesia",
    "nativeName": "Polynésie française",
    "capital": "Papeete",
    "continent": "Oceania",
    "currency": "Franc",
    "callingCode": "689",
    "timeZoneInCapital": "Pacific/Tahiti",
    "alpha2": "PF",
    "alpha3": "PYF",
    "numeric": "258",
    "tld": "pf",
    "fips": "FP"
  },
  "PG": {
    "name": "Papua New Guinea",
    "shortName": "Papua New Guinea",
    "nativeName": "Papua Niugini",
    "capital": "Port Moresby",
    "continent": "Oceania",
    "currency": "Kina",
    "callingCode": "675",
    "timeZoneInCapital": "Pacific/Port_Moresby",
    "alpha2": "PG",
    "alpha3": "PNG",
    "numeric": "598",
    "tld": "pg",
    "fips": "PP"
  },
  "PH": {
    "name": "Philippines (the)",
    "shortName": "Philippines",
    "nativeName": "Pilipinas",
    "capital": "Manila",
    "continent": "Asia",
    "currency": "Peso",
    "callingCode": "63",
    "timeZoneInCapital": "Asia/Manila",
    "alpha2": "PH",
    "alpha3": "PHL",
    "numeric": "608",
    "tld": "ph",
    "fips": "RP"
  },
  "PK": {
    "name": "Pakistan",
    "shortName": "Pakistan",
    "nativeName": "Pakistan",
    "capital": "Islamabad",
    "continent": "Asia",
    "currency": "Rupee",
    "callingCode": "92",
    "timeZoneInCapital": "Asia/Karachi",
    "alpha2": "PK",
    "alpha3": "PAK",
    "numeric": "586",
    "tld": "pk",
    "fips": "PK"
  },
  "PL": {
    "name": "Poland",
    "shortName": "Poland",
    "nativeName": "Polska",
    "capital": "Warsaw",
    "continent": "Europe",
    "currency": "Zloty",
    "callingCode": "48",
    "timeZoneInCapital": "Europe/Warsaw",
    "alpha2": "PL",
    "alpha3": "POL",
    "numeric": "616",
    "tld": "pl",
    "fips": "PL"
  },
  "PM": {
    "name": "Saint Pierre and Miquelon",
    "shortName": "Saint Pierre and Miquelon",
    "nativeName": "Saint-Pierre-et-Miquelon",
    "capital": "Saint-Pierre",
    "continent": "North America",
    "currency": "Euro",
    "callingCode": "508",
    "timeZoneInCapital": "America/Miquelon",
    "alpha2": "PM",
    "alpha3": "SPM",
    "numeric": "666",
    "tld": "pm",
    "fips": "SB"
  },
  "PN": {
    "name": "Pitcairn",
    "shortName": "Pitcairn",
    "nativeName": "Pitcairn Islands",
    "capital": "Adamstown",
    "continent": "Oceania",
    "currency": "Dollar",
    "callingCode": "64",
    "timeZoneInCapital": "Pacific/Pitcairn",
    "alpha2": "PN",
    "alpha3": "PCN",
    "numeric": "612",
    "tld": "pn",
    "fips": "PC"
  },
  "PR": {
    "name": "Puerto Rico",
    "shortName": "Puerto Rico",
    "nativeName": "Puerto Rico",
    "capital": "San Juan",
    "continent": "North America",
    "currency": "Dollar",
    "callingCode": "1-787, 1-939",
    "timeZoneInCapital": "America/Puerto_Rico",
    "alpha2": "PR",
    "alpha3": "PRI",
    "numeric": "630",
    "tld": "pr",
    "fips": "RQ"
  },
  "PS": {
    "name": "Palestine, State of",
    "shortName": "Palestine",
    "nativeName": "فلسطين",
    "capital": "East Jerusalem",
    "continent": "Asia",
    "currency": "Shekel",
    "callingCode": "970",
    "timeZoneInCapital": "Asia/Hebron",
    "alpha2": "PS",
    "alpha3": "PSE",
    "numeric": "275",
    "tld": "ps",
    "fips": "WE"
  },
  "PT": {
    "name": "Portugal",
    "shortName": "Portugal",
    "nativeName": "Portugal",
    "capital": "Lisbon",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "351",
    "timeZoneInCapital": "Europe/Lisbon",
    "alpha2": "PT",
    "alpha3": "PRT",
    "numeric": "620",
    "tld": "pt",
    "fips": "PO"
  },
  "PW": {
    "name": "Palau",
    "shortName": "Palau",
    "nativeName": "Palau",
    "capital": "Melekeok",
    "continent": "Oceania",
    "currency": "Dollar",
    "callingCode": "680",
    "timeZoneInCapital": "Pacific/Palau",
    "alpha2": "PW",
    "alpha3": "PLW",
    "numeric": "585",
    "tld": "pw",
    "fips": "PS"
  },
  "PY": {
    "name": "Paraguay",
    "shortName": "Paraguay",
    "nativeName": "Paraguay",
    "capital": "Asuncion",
    "continent": "South America",
    "currency": "Guarani",
    "callingCode": "595",
    "timeZoneInCapital": "America/Asuncion",
    "alpha2": "PY",
    "alpha3": "PRY",
    "numeric": "600",
    "tld": "py",
    "fips": "PA"
  },
  "QA": {
    "name": "Qatar",
    "shortName": "Qatar",
    "nativeName": "قطر",
    "capital": "Doha",
    "continent": "Asia",
    "currency": "Rial",
    "callingCode": "974",
    "timeZoneInCapital": "Asia/Qatar",
    "alpha2": "QA",
    "alpha3": "QAT",
    "numeric": "634",
    "tld": "qa",
    "fips": "QA"
  },
  "RE": {
    "name": "Réunion",
    "shortName": "Reunion",
    "nativeName": "La Réunion",
    "capital": "Saint-Denis",
    "continent": "Africa",
    "currency": "Euro",
    "callingCode": "262",
    "timeZoneInCapital": "Indian/Reunion",
    "alpha2": "RE",
    "alpha3": "REU",
    "numeric": "638",
    "tld": "re",
    "fips": "RE"
  },
  "RO": {
    "name": "Romania",
    "shortName": "Romania",
    "nativeName": "România",
    "capital": "Bucharest",
    "continent": "Europe",
    "currency": "Leu",
    "callingCode": "40",
    "timeZoneInCapital": "Europe/Bucharest",
    "alpha2": "RO",
    "alpha3": "ROU",
    "numeric": "642",
    "tld": "ro",
    "fips": "RO"
  },
  "RS": {
    "name": "Serbia",
    "shortName": "Serbia",
    "nativeName": "Србија",
    "capital": "Belgrade",
    "continent": "Europe",
    "currency": "Dinar",
    "callingCode": "381",
    "timeZoneInCapital": "Europe/Belgrade",
    "alpha2": "RS",
    "alpha3": "SRB",
    "numeric": "688",
    "tld": "rs",
    "fips": "RI"
  },
  "RU": {
    "name": "Russian Federation (the)",
    "shortName": "Russia",
    "nativeName": "Россия",
    "capital": "Moscow",
    "continent": "Europe",
    "currency": "Ruble",
    "callingCode": "7",
    "timeZoneInCapital": "Europe/Moscow",
    "alpha2": "RU",
    "alpha3": "RUS",
    "numeric": "643",
    "tld": "ru",
    "fips": "RS"
  },
  "RW": {
    "name": "Rwanda",
    "shortName": "Rwanda",
    "nativeName": "Rwanda",
    "capital": "Kigali",
    "continent": "Africa",
    "currency": "Franc",
    "callingCode": "250",
    "timeZoneInCapital": "Africa/Maputo",
    "alpha2": "RW",
    "alpha3": "RWA",
    "numeric": "646",
    "tld": "rw",
    "fips": "RW"
  },
  "SA": {
    "name": "Saudi Arabia",
    "shortName": "Saudi Arabia",
    "nativeName": "العربية السعودية",
    "capital": "Riyadh",
    "continent": "Asia",
    "currency": "Rial",
    "callingCode": "966",
    "timeZoneInCapital": "Asia/Riyadh",
    "alpha2": "SA",
    "alpha3": "SAU",
    "numeric": "682",
    "tld": "sa",
    "fips": "SA"
  },
  "SB": {
    "name": "Solomon Islands",
    "shortName": "Solomon Islands",
    "nativeName": "Solomon Islands",
    "capital": "Honiara",
    "continent": "Oceania",
    "currency": "Dollar",
    "callingCode": "677",
    "timeZoneInCapital": "Pacific/Guadalcanal",
    "alpha2": "SB",
    "alpha3": "SLB",
    "numeric": "90",
    "tld": "sb",
    "fips": "BP"
  },
  "SC": {
    "name": "Seychelles",
    "shortName": "Seychelles",
    "nativeName": "Seychelles",
    "capital": "Victoria",
    "continent": "Africa",
    "currency": "Rupee",
    "callingCode": "248",
    "timeZoneInCapital": "Indian/Mahe",
    "alpha2": "SC",
    "alpha3": "SYC",
    "numeric": "690",
    "tld": "sc",
    "fips": "SE"
  },
  "SD": {
    "name": "Sudan (the)",
    "shortName": "Sudan",
    "nativeName": "السودان",
    "capital": "Khartoum",
    "continent": "Africa",
    "currency": "Pound",
    "callingCode": "249",
    "timeZoneInCapital": "Africa/Khartoum",
    "alpha2": "SD",
    "alpha3": "SDN",
    "numeric": "729",
    "tld": "sd",
    "fips": "SU"
  },
  "SE": {
    "name": "Sweden",
    "shortName": "Sweden",
    "nativeName": "Sverige",
    "capital": "Stockholm",
    "continent": "Europe",
    "currency": "Krona",
    "callingCode": "46",
    "timeZoneInCapital": "Europe/Stockholm",
    "alpha2": "SE",
    "alpha3": "SWE",
    "numeric": "752",
    "tld": "se",
    "fips": "SW"
  },
  "SG": {
    "name": "Singapore",
    "shortName": "Singapore",
    "nativeName": "Singapore",
    "capital": "Singapore",
    "continent": "Asia",
    "currency": "Dollar",
    "callingCode": "65",
    "timeZoneInCapital": "Asia/Singapore",
    "alpha2": "SG",
    "alpha3": "SGP",
    "numeric": "702",
    "tld": "sg",
    "fips": "SN"
  },
  "SH": {
    "name": "Saint Helena, Ascension and Tristan da Cunha",
    "shortName": "Saint Helena",
    "nativeName": "Saint Helena",
    "capital": "Jamestown",
    "continent": "Africa",
    "currency": "Pound",
    "callingCode": "290",
    "timeZoneInCapital": "Africa/Abidjan",
    "alpha2": "SH",
    "alpha3": "SHN",
    "numeric": "654",
    "tld": "sh",
    "fips": "SH"
  },
  "SI": {
    "name": "Slovenia",
    "shortName": "Slovenia",
    "nativeName": "Slovenija",
    "capital": "Ljubljana",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "386",
    "timeZoneInCapital": "Europe/Belgrade",
    "alpha2": "SI",
    "alpha3": "SVN",
    "numeric": "705",
    "tld": "si",
    "fips": "SI"
  },
  "SJ": {
    "name": "Svalbard and Jan Mayen",
    "shortName": "Svalbard and Jan Mayen",
    "nativeName": "Svalbard og Jan Mayen",
    "capital": "Longyearbyen",
    "continent": "Europe",
    "currency": "Krone",
    "callingCode": "47",
    "timeZoneInCapital": "Europe/Oslo",
    "alpha2": "SJ",
    "alpha3": "SJM",
    "numeric": "744",
    "tld": "sj",
    "fips": "SV"
  },
  "SK": {
    "name": "Slovakia",
    "shortName": "Slovakia",
    "nativeName": "Slovensko",
    "capital": "Bratislava",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "421",
    "timeZoneInCapital": "Europe/Prague",
    "alpha2": "SK",
    "alpha3": "SVK",
    "numeric": "703",
    "tld": "sk",
    "fips": "LO"
  },
  "SL": {
    "name": "Sierra Leone",
    "shortName": "Sierra Leone",
    "nativeName": "Sierra Leone",
    "capital": "Freetown",
    "continent": "Africa",
    "currency": "Leone",
    "callingCode": "232",
    "timeZoneInCapital": "Africa/Abidjan",
    "alpha2": "SL",
    "alpha3": "SLE",
    "numeric": "694",
    "tld": "sl",
    "fips": "SL"
  },
  "SM": {
    "name": "San Marino",
    "shortName": "San Marino",
    "nativeName": "San Marino",
    "capital": "San Marino",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "378",
    "timeZoneInCapital": "Europe/Rome",
    "alpha2": "SM",
    "alpha3": "SMR",
    "numeric": "674",
    "tld": "sm",
    "fips": "SM"
  },
  "SN": {
    "name": "Senegal",
    "shortName": "Senegal",
    "nativeName": "Sénégal",
    "capital": "Dakar",
    "continent": "Africa",
    "currency": "Franc",
    "callingCode": "221",
    "timeZoneInCapital": "Africa/Abidjan",
    "alpha2": "SN",
    "alpha3": "SEN",
    "numeric": "686",
    "tld": "sn",
    "fips": "SG"
  },
  "SO": {
    "name": "Somalia",
    "shortName": "Somalia",
    "nativeName": "Soomaaliya",
    "capital": "Mogadishu",
    "continent": "Africa",
    "currency": "Shilling",
    "callingCode": "252",
    "timeZoneInCapital": "Africa/Mogadishu",
    "alpha2": "SO",
    "alpha3": "SOM",
    "numeric": "706",
    "tld": "so",
    "fips": "SO"
  },
  "SR": {
    "name": "Suriname",
    "shortName": "Suriname",
    "nativeName": "Suriname",
    "capital": "Paramaribo",
    "continent": "South America",
    "currency": "Dollar",
    "callingCode": "597",
    "timeZoneInCapital": "America/Paramaribo",
    "alpha2": "SR",
    "alpha3": "SUR",
    "numeric": "740",
    "tld": "sr",
    "fips": "NS"
  },
  "SS": {
    "name": "South Sudan",
    "shortName": "South Sudan",
    "nativeName": "South Sudan",
    "capital": "Juba",
    "continent": "Africa",
    "currency": "Pound",
    "callingCode": "211",
    "timeZoneInCapital": "Africa/Khartoum",
    "alpha2": "SS",
    "alpha3": "SSD",
    "numeric": "728",
    "tld": "ss",
    "fips": "OD"
  },
  "ST": {
    "name": "Sao Tome and Principe",
    "shortName": "Sao Tome and Principe",
    "nativeName": "São Tomé e Príncipe",
    "capital": "Sao Tome",
    "continent": "Africa",
    "currency": "Dobra",
    "callingCode": "239",
    "timeZoneInCapital": "Africa/Abidjan",
    "alpha2": "ST",
    "alpha3": "STP",
    "numeric": "678",
    "tld": "st",
    "fips": "TP"
  },
  "SV": {
    "name": "El Salvador",
    "shortName": "El Salvador",
    "nativeName": "El Salvador",
    "capital": "San Salvador",
    "continent": "North America",
    "currency": "Dollar",
    "callingCode": "503",
    "timeZoneInCapital": "America/El_Salvador",
    "alpha2": "SV",
    "alpha3": "SLV",
    "numeric": "222",
    "tld": "sv",
    "fips": "ES"
  },
  "SX": {
    "name": "Sint Maarten (Dutch part)",
    "shortName": "Sint Maarten",
    "nativeName": "South Georgia and the South Sandwich Islands",
    "capital": "Philipsburg",
    "continent": "North America",
    "currency": "Guilder",
    "callingCode": "1-721",
    "timeZoneInCapital": "America/Curacao",
    "alpha2": "SX",
    "alpha3": "SXM",
    "numeric": "534",
    "tld": "sx",
    "fips": "NN"
  },
  "SY": {
    "name": "Syrian Arab Republic (the)",
    "shortName": "Syria",
    "nativeName": "سوريا",
    "capital": "Damascus",
    "continent": "Asia",
    "currency": "Pound",
    "callingCode": "963",
    "timeZoneInCapital": "Asia/Damascus",
    "alpha2": "SY",
    "alpha3": "SYR",
    "numeric": "760",
    "tld": "sy",
    "fips": "SY"
  },
  "SZ": {
    "name": "Eswatini",
    "shortName": "Swaziland",
    "nativeName": "Swaziland",
    "capital": "Mbabane",
    "continent": "Africa",
    "currency": "Lilangeni",
    "callingCode": "268",
    "timeZoneInCapital": "Africa/Johannesburg",
    "alpha2": "SZ",
    "alpha3": "SWZ",
    "numeric": "748",
    "tld": "sz",
    "fips": "WZ"
  },
  "TC": {
    "name": "Turks and Caicos Islands (the)",
    "shortName": "Turks and Caicos Islands",
    "nativeName": "Turks and Caicos Islands",
    "capital": "Cockburn Town",
    "continent": "North America",
    "currency": "Dollar",
    "callingCode": "1-649",
    "timeZoneInCapital": "America/Grand_Turk",
    "alpha2": "TC",
    "alpha3": "TCA",
    "numeric": "796",
    "tld": "tc",
    "fips": "TK"
  },
  "TD": {
    "name": "Chad",
    "shortName": "Chad",
    "nativeName": "Tchad",
    "capital": "N'Djamena",
    "continent": "Africa",
    "currency": "Franc",
    "callingCode": "235",
    "timeZoneInCapital": "Africa/Ndjamena",
    "alpha2": "TD",
    "alpha3": "TCD",
    "numeric": "148",
    "tld": "td",
    "fips": "CD"
  },
  "TF": {
    "name": "French Southern Territories (the)",
    "shortName": "French Southern Territories",
    "nativeName": "Territoire des Terres australes et antarctiques fr",
    "capital": "Saint Pierre, Réunion",
    "continent": "Africa",
    "currency": "Euro",
    "callingCode": "262",
    "timeZoneInCapital": "Indian/Kerguelen",
    "alpha2": "TF",
    "alpha3": "ATF",
    "numeric": "260",
    "tld": "tf",
    "fips": "FS"
  },
  "TG": {
    "name": "Togo",
    "shortName": "Togo",
    "nativeName": "Togo",
    "capital": "Lome",
    "continent": "Africa",
    "currency": "Franc",
    "callingCode": "228",
    "timeZoneInCapital": "Africa/Abidjan",
    "alpha2": "TG",
    "alpha3": "TGO",
    "numeric": "768",
    "tld": "tg",
    "fips": "TO"
  },
  "TH": {
    "name": "Thailand",
    "shortName": "Thailand",
    "nativeName": "ประเทศไทย",
    "capital": "Bangkok",
    "continent": "Asia",
    "currency": "Baht",
    "callingCode": "66",
    "timeZoneInCapital": "Asia/Bangkok",
    "alpha2": "TH",
    "alpha3": "THA",
    "numeric": "764",
    "tld": "th",
    "fips": "TH"
  },
  "TJ": {
    "name": "Tajikistan",
    "shortName": "Tajikistan",
    "nativeName": "Тоҷикистон",
    "capital": "Dushanbe",
    "continent": "Asia",
    "currency": "Somoni",
    "callingCode": "992",
    "timeZoneInCapital": "Asia/Dushanbe",
    "alpha2": "TJ",
    "alpha3": "TJK",
    "numeric": "762",
    "tld": "tj",
    "fips": "TI"
  },
  "TK": {
    "name": "Tokelau",
    "shortName": "Tokelau",
    "nativeName": "Tokelau",
    "capital": "Fakaofo",
    "continent": "Oceania",
    "currency": "Dollar",
    "callingCode": "690",
    "timeZoneInCapital": "Pacific/Fakaofo",
    "alpha2": "TK",
    "alpha3": "TKL",
    "numeric": "772",
    "tld": "tk",
    "fips": "TL"
  },
  "TL": {
    "name": "Timor-Leste",
    "shortName": "East Timor",
    "nativeName": "Timor-Leste",
    "capital": "Dili",
    "continent": "Oceania",
    "currency": "Dollar",
    "callingCode": "670",
    "timeZoneInCapital": "Asia/Dili",
    "alpha2": "TL",
    "alpha3": "TLS",
    "numeric": "626",
    "tld": "tl",
    "fips": "TT"
  },
  "TM": {
    "name": "Turkmenistan",
    "shortName": "Turkmenistan",
    "nativeName": "Türkmenistan",
    "capital": "Ashgabat",
    "continent": "Asia",
    "currency": "Manat",
    "callingCode": "993",
    "timeZoneInCapital": "Asia/Ashgabat",
    "alpha2": "TM",
    "alpha3": "TKM",
    "numeric": "795",
    "tld": "tm",
    "fips": "TX"
  },
  "TN": {
    "name": "Tunisia",
    "shortName": "Tunisia",
    "nativeName": "تونس",
    "capital": "Tunis",
    "continent": "Africa",
    "currency": "Dinar",
    "callingCode": "216",
    "timeZoneInCapital": "Africa/Tunis",
    "alpha2": "TN",
    "alpha3": "TUN",
    "numeric": "788",
    "tld": "tn",
    "fips": "TS"
  },
  "TO": {
    "name": "Tonga",
    "shortName": "Tonga",
    "nativeName": "Tonga",
    "capital": "Nuku'alofa",
    "continent": "Oceania",
    "currency": "Pa'anga",
    "callingCode": "676",
    "timeZoneInCapital": "Pacific/Tongatapu",
    "alpha2": "TO",
    "alpha3": "TON",
    "numeric": "776",
    "tld": "to",
    "fips": "TN"
  },
  "TR": {
    "name": "Turkey",
    "shortName": "Turkey",
    "nativeName": "Türkiye",
    "capital": "Ankara",
    "continent": "Asia",
    "currency": "Lira",
    "callingCode": "90",
    "timeZoneInCapital": "Europe/Istanbul",
    "alpha2": "TR",
    "alpha3": "TUR",
    "numeric": "792",
    "tld": "tr",
    "fips": "TU"
  },
  "TT": {
    "name": "Trinidad and Tobago",
    "shortName": "Trinidad and Tobago",
    "nativeName": "Trinidad and Tobago",
    "capital": "Port of Spain",
    "continent": "North America",
    "currency": "Dollar",
    "callingCode": "1-868",
    "timeZoneInCapital": "America/Port_of_Spain",
    "alpha2": "TT",
    "alpha3": "TTO",
    "numeric": "780",
    "tld": "tt",
    "fips": "TD"
  },
  "TV": {
    "name": "Tuvalu",
    "shortName": "Tuvalu",
    "nativeName": "Tuvalu",
    "capital": "Funafuti",
    "continent": "Oceania",
    "currency": "Dollar",
    "callingCode": "688",
    "timeZoneInCapital": "Pacific/Funafuti",
    "alpha2": "TV",
    "alpha3": "TUV",
    "numeric": "798",
    "tld": "tv",
    "fips": "TV"
  },
  "TW": {
    "name": "Taiwan (China)",
    "shortName": "Taiwan",
    "nativeName": "臺灣",
    "capital": "Taipei",
    "continent": "Asia",
    "currency": "Dollar",
    "callingCode": "886",
    "timeZoneInCapital": "Asia/Taipei",
    "alpha2": "TW",
    "alpha3": "TWN",
    "numeric": "158",
    "tld": "tw",
    "fips": "TW"
  },
  "TZ": {
    "name": "Tanzania, the United Republic of",
    "shortName": "Tanzania",
    "nativeName": "Tanzania",
    "capital": "Dodoma",
    "continent": "Africa",
    "currency": "Shilling",
    "callingCode": "255",
    "timeZoneInCapital": "Africa/Dar_es_Salaam",
    "alpha2": "TZ",
    "alpha3": "TZA",
    "numeric": "834",
    "tld": "tz",
    "fips": "TZ"
  },
  "UA": {
    "name": "Ukraine",
    "shortName": "Ukraine",
    "nativeName": "Україна",
    "capital": "Kiev",
    "continent": "Europe",
    "currency": "Hryvnia",
    "callingCode": "380",
    "timeZoneInCapital": "Europe/Kiev",
    "alpha2": "UA",
    "alpha3": "UKR",
    "numeric": "804",
    "tld": "ua",
    "fips": "UP"
  },
  "UG": {
    "name": "Uganda",
    "shortName": "Uganda",
    "nativeName": "Uganda",
    "capital": "Kampala",
    "continent": "Africa",
    "currency": "Shilling",
    "callingCode": "256",
    "timeZoneInCapital": "Africa/Kampala",
    "alpha2": "UG",
    "alpha3": "UGA",
    "numeric": "800",
    "tld": "ug",
    "fips": "UG"
  },
  "UM": {
    "name": "United States Minor Outlying Islands (the)",
    "shortName": "United States Outlying Islands",
    "nativeName": "United States Minor Outlying Islands",
    "capital": "Washington",
    "continent": "Oceania",
    "currency": "Dollar",
    "callingCode": "268",
    "timeZoneInCapital": "Pacific/Wake",
    "alpha2": "UM",
    "alpha3": "UMI",
    "numeric": "581",
    "tld": "us",
    "fips": "FQ"
  },
  "US": {
    "name": "United States of America (the)",
    "shortName": "USA",
    "nativeName": "United States",
    "capital": "Washington",
    "continent": "North America",
    "currency": "Dollar",
    "callingCode": "1",
    "timeZoneInCapital": "America/New_York",
    "alpha2": "US",
    "alpha3": "USA",
    "numeric": "840",
    "tld": "us",
    "fips": "US"
  },
  "UY": {
    "name": "Uruguay",
    "shortName": "Uruguay",
    "nativeName": "Uruguay",
    "capital": "Montevideo",
    "continent": "South America",
    "currency": "Peso",
    "callingCode": "598",
    "timeZoneInCapital": "America/Montevideo",
    "alpha2": "UY",
    "alpha3": "URY",
    "numeric": "858",
    "tld": "uy",
    "fips": "UY"
  },
  "UZ": {
    "name": "Uzbekistan",
    "shortName": "Uzbekistan",
    "nativeName": "O‘zbekiston",
    "capital": "Tashkent",
    "continent": "Asia",
    "currency": "Som",
    "callingCode": "998",
    "timeZoneInCapital": "Asia/Tashkent",
    "alpha2": "UZ",
    "alpha3": "UZB",
    "numeric": "860",
    "tld": "uz",
    "fips": "UZ"
  },
  "VA": {
    "name": "Holy See (the)",
    "shortName": "Vatican",
    "nativeName": "Vaticano",
    "capital": "Vatican City",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "379",
    "timeZoneInCapital": "Europe/Rome",
    "alpha2": "VA",
    "alpha3": "VAT",
    "numeric": "336",
    "tld": "va",
    "fips": "VT"
  },
  "VC": {
    "name": "Saint Vincent and the Grenadines",
    "shortName": "Saint Vincent and the Grenadines",
    "nativeName": "Saint Vincent and the Grenadines",
    "capital": "Kingstown",
    "continent": "North America",
    "currency": "Dollar",
    "callingCode": "1-784",
    "timeZoneInCapital": "America/Port_of_Spain",
    "alpha2": "VC",
    "alpha3": "VCT",
    "numeric": "670",
    "tld": "vc",
    "fips": "VC"
  },
  "VE": {
    "name": "Venezuela (Bolivarian Republic of)",
    "shortName": "Venezuela",
    "nativeName": "Venezuela",
    "capital": "Caracas",
    "continent": "South America",
    "currency": "Bolivar",
    "callingCode": "58",
    "timeZoneInCapital": "America/Caracas",
    "alpha2": "VE",
    "alpha3": "VEN",
    "numeric": "862",
    "tld": "ve",
    "fips": "VE"
  },
  "VG": {
    "name": "Virgin Islands (British)",
    "shortName": "British Virgin Islands",
    "nativeName": "British Virgin Islands",
    "capital": "Road Town",
    "continent": "North America",
    "currency": "Dollar",
    "callingCode": "1-284",
    "timeZoneInCapital": "America/Port_of_Spain",
    "alpha2": "VG",
    "alpha3": "VGB",
    "numeric": "92",
    "tld": "vg",
    "fips": "VI"
  },
  "VI": {
    "name": "Virgin Islands (U.S.)",
    "shortName": "U.S. Virgin Islands",
    "nativeName": "United States Virgin Islands",
    "capital": "Charlotte Amalie",
    "continent": "North America",
    "currency": "Dollar",
    "callingCode": "1-340",
    "timeZoneInCapital": "America/Port_of_Spain",
    "alpha2": "VI",
    "alpha3": "VIR",
    "numeric": "850",
    "tld": "vi",
    "fips": "VQ"
  },
  "VN": {
    "name": "Viet Nam",
    "shortName": "Vietnam",
    "nativeName": "Việt Nam",
    "capital": "Hanoi",
    "continent": "Asia",
    "currency": "Dong",
    "callingCode": "84",
    "timeZoneInCapital": "Asia/Ho_Chi_Minh",
    "alpha2": "VN",
    "alpha3": "VNM",
    "numeric": "704",
    "tld": "vn",
    "fips": "VM"
  },
  "VU": {
    "name": "Vanuatu",
    "shortName": "Vanuatu",
    "nativeName": "Vanuatu",
    "capital": "Port Vila",
    "continent": "Oceania",
    "currency": "Vatu",
    "callingCode": "678",
    "timeZoneInCapital": "Pacific/Efate",
    "alpha2": "VU",
    "alpha3": "VUT",
    "numeric": "548",
    "tld": "vu",
    "fips": "NH"
  },
  "WF": {
    "name": "Wallis and Futuna",
    "shortName": "Wallis and Futuna",
    "nativeName": "Wallis et Futuna",
    "capital": "Mata Utu",
    "continent": "Oceania",
    "currency": "Franc",
    "callingCode": "681",
    "timeZoneInCapital": "Pacific/Wallis",
    "alpha2": "WF",
    "alpha3": "WLF",
    "numeric": "876",
    "tld": "wf",
    "fips": "WF"
  },
  "WS": {
    "name": "Samoa",
    "shortName": "Samoa",
    "nativeName": "Samoa",
    "capital": "Apia",
    "continent": "Oceania",
    "currency": "Tala",
    "callingCode": "685",
    "timeZoneInCapital": "Pacific/Apia",
    "alpha2": "WS",
    "alpha3": "WSM",
    "numeric": "882",
    "tld": "ws",
    "fips": "WS"
  },
  "XK": {
    "name": "Republic of Kosovo",
    "shortName": "Kosovo",
    "nativeName": "Republika e Kosovës",
    "capital": "Pristina",
    "continent": "Europe",
    "currency": "Euro",
    "callingCode": "383",
    "timeZoneInCapital": "Europe/Belgrade",
    "alpha2": "XK",
    "alpha3": "XKX",
    "numeric": "",
    "tld": "xk",
    "fips": "KV"
  },
  "YE": {
    "name": "Yemen",
    "shortName": "Yemen",
    "nativeName": "اليَمَن",
    "capital": "Sanaa",
    "continent": "Asia",
    "currency": "Rial",
    "callingCode": "967",
    "timeZoneInCapital": "Asia/Aden",
    "alpha2": "YE",
    "alpha3": "YEM",
    "numeric": "887",
    "tld": "ye",
    "fips": "YM"
  },
  "YT": {
    "name": "Mayotte",
    "shortName": "Mayotte",
    "nativeName": "Mayotte",
    "capital": "Mamoudzou",
    "continent": "Africa",
    "currency": "Euro",
    "callingCode": "262",
    "timeZoneInCapital": "Indian/Mayotte",
    "alpha2": "YT",
    "alpha3": "MYT",
    "numeric": "175",
    "tld": "yt",
    "fips": "MF"
  },
  "ZA": {
    "name": "South Africa",
    "shortName": "South Africa",
    "nativeName": "South Africa",
    "capital": "Pretoria",
    "continent": "Africa",
    "currency": "Rand",
    "callingCode": "27",
    "timeZoneInCapital": "Africa/Johannesburg",
    "alpha2": "ZA",
    "alpha3": "ZAF",
    "numeric": "710",
    "tld": "za",
    "fips": "SF"
  },
  "ZM": {
    "name": "Zambia",
    "shortName": "Zambia",
    "nativeName": "Zambia",
    "capital": "Lusaka",
    "continent": "Africa",
    "currency": "Kwacha",
    "callingCode": "260",
    "timeZoneInCapital": "Africa/Maputo",
    "alpha2": "ZM",
    "alpha3": "ZMB",
    "numeric": "894",
    "tld": "zm",
    "fips": "ZA"
  },
  "ZW": {
    "name": "Zimbabwe",
    "shortName": "Zimbabwe",
    "nativeName": "Zimbabwe",
    "capital": "Harare",
    "continent": "Africa",
    "currency": "Dollar",
    "callingCode": "263",
    "timeZoneInCapital": "Africa/Maputo",
    "alpha2": "ZW",
    "alpha3": "ZWE",
    "numeric": "716",
    "tld": "zw",
    "fips": "ZI"
  }
};